import type { VariableConfig } from '../../types/country'
import { DATA_SOURCES, VARIABLES } from './variables'

/** Variable configs missing from GitHub main VARIABLES (unused stats + 4 new datasets). */
export const EXTRA_VARIABLES: Record<string, VariableConfig> = {
  'conflict.militarySpendingGdp': {
    id: 'conflict.militarySpendingGdp',
    name: 'Military Spending (% GDP)',
    description: 'Military expenditure as a share of GDP (SIPRI via Our World in Data, latest year per country, 1999–2025)',
    category: 'safety',
    type: 'numeric',
    domain: [0, 10],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
    leadWithHigh: true,
  },
  'freedom.cannabisLegal': {
    id: 'freedom.cannabisLegal',
    name: 'Cannabis Legal',
    description: 'Whether recreational cannabis is legal',
    category: 'governance',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolateGreens',
    format: (v) => v === null || v === undefined ? 'N/A' : (Number(v) ? 'Yes' : 'No'),
    higherIsBetter: true,
  },
  'freedom.drugPolicyScore': {
    id: 'freedom.drugPolicyScore',
    name: 'Drug Policy Score',
    description: 'How liberal national drug policy is (0-100, 100 = most liberal)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.gamblingLegal': {
    id: 'freedom.gamblingLegal',
    name: 'Gambling Legal',
    description: 'Whether gambling is legal',
    category: 'governance',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolateGreens',
    format: (v) => v === null || v === undefined ? 'N/A' : (Number(v) ? 'Yes' : 'No'),
    higherIsBetter: true,
  },
  'freedom.passportPower': {
    id: 'freedom.passportPower',
    name: 'Passport Power',
    description: 'Visa-free and visa-on-arrival destinations (Arton Capital Passport Index, 2026)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 180],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)} destinations` : 'N/A',
    higherIsBetter: true,
  },
  'health.smokingRate': {
    id: 'health.smokingRate',
    name: 'Smoking Rate',
    description: 'Percentage of adults who smoke',
    category: 'health',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'religion.importance': {
    id: 'religion.importance',
    name: 'Religion Very Important',
    description: "Share of people who say religion is 'very important' in their life (Pew / World Values Survey via Our World in Data, latest survey year per country)",
    category: 'religion',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'sex.childMarriageRate': {
    id: 'sex.childMarriageRate',
    name: 'Child Marriage Rate',
    description: 'Share of women aged 20–24 first married by 18 (UNICEF SDG 5.3.1 via Our World in Data, latest survey year per country)',
    category: 'sex',
    type: 'numeric',
    domain: [0, 80],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
    leadWithHigh: true,
  },
  'sex.marriageAge': {
    id: 'sex.marriageAge',
    name: 'Marriage Age',
    description: 'Average age at first marriage (years)',
    category: 'sex',
    type: 'numeric',
    domain: [15, 40],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'sex.polyamoryRate': {
    id: 'sex.polyamoryRate',
    name: 'Polyamory Rate',
    description: 'Percentage of adults in open or polyamorous relationships',
    category: 'sex',
    type: 'numeric',
    domain: [0, 10],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'sex.prostitutionLegal': {
    id: 'sex.prostitutionLegal',
    name: 'Prostitution Legal',
    description: 'Whether prostitution is legal',
    category: 'sex',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolateGreens',
    format: (v) => v === null || v === undefined ? 'N/A' : (Number(v) ? 'Yes' : 'No'),
    higherIsBetter: true,
  },
  'sex.teenPregnancy': {
    id: 'sex.teenPregnancy',
    name: 'Teen Pregnancy Rate',
    description: 'Births per 1,000 women aged 15-19',
    category: 'sex',
    type: 'numeric',
    domain: [0, 200],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: false,
  },
}

export const EXTRA_DATA_SOURCES = {
  passport_index: {
    name: 'Arton Capital Passport Index',
    url: 'https://github.com/imorte/passport-index-data',
    description: 'Visa-free and visa-on-arrival destination counts by passport',
  },
  sipri: {
    name: 'SIPRI',
    url: 'https://www.sipri.org/databases/milex',
    description: 'Military expenditure as a share of GDP, via Our World in Data',
  },
  unicef: {
    name: 'UNICEF',
    url: 'https://data.unicef.org/topic/child-protection/child-marriage/',
    description: 'SDG 5.3.1 child marriage: share of women 20–24 married by 18, via Our World in Data',
  },
  wvs_pew: {
    name: 'World Values Survey / Pew Research Center',
    url: 'https://ourworldindata.org/grapher/how-important-religion-is-in-your-life',
    description: 'Share of people who say religion is very important in their life, via Our World in Data',
  },
}

Object.assign(VARIABLES, EXTRA_VARIABLES)
Object.assign(DATA_SOURCES, EXTRA_DATA_SOURCES)
