import type { VariableConfig, ColorVariable } from '@/types/country'

export const MAJOR_RELIGIONS = [
  'Christianity',
  'Islam',
  'Hinduism',
  'Buddhism',
  'Judaism',
  'Folk/Traditional',
  'Other',
  'None/Unaffiliated',
] as const

export const REGIONS = [
  'Africa',
  'Americas',
  'Asia',
  'Europe',
  'Oceania',
] as const

export const VARIABLE_CATEGORIES = [
  { id: 'governance', name: 'Governance & Freedom', icon: '🏛️' },
  { id: 'economy', name: 'Economy & Wealth', icon: '💰' },
  { id: 'health', name: 'Health & Body', icon: '🏥' },
  { id: 'sex', name: 'Sex & Relationships', icon: '❤️' },
  { id: 'demographics', name: 'Demographics', icon: '👥' },
  { id: 'education', name: 'Intelligence & Education', icon: '🎓' },
  { id: 'lifestyle', name: 'Lifestyle & Happiness', icon: '😊' },
  { id: 'safety', name: 'Safety & Crime', icon: '🛡️' },
  { id: 'religion', name: 'Religion', icon: '🙏' },
] as const

export const VARIABLES: Record<ColorVariable, VariableConfig> = {
  // === GOVERNANCE & FREEDOM ===
  'democracy.score': {
    id: 'democracy.score',
    name: 'Democracy Score',
    description: 'Combined democracy index (0-100) based on V-Dem and Freedom House data',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.corruptionIndex': {
    id: 'freedom.corruptionIndex',
    name: 'Corruption Index',
    description: 'Transparency International CPI (0=most corrupt, 100=cleanest)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.pressFreedom': {
    id: 'freedom.pressFreedom',
    name: 'Press Freedom',
    description: 'Reporters Without Borders index (0-100, higher = more free)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },

  // === ECONOMY & WEALTH ===
  'poverty.gdpPerCapita': {
    id: 'poverty.gdpPerCapita',
    name: 'GDP per Capita',
    description: 'GDP per capita in USD (PPP)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100000],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `$${(v as number).toLocaleString()}` : 'N/A',
    higherIsBetter: true,
  },
  'poverty.hdi': {
    id: 'poverty.hdi',
    name: 'Human Development Index',
    description: 'UN Human Development Index (0-1)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? (v as number).toFixed(3) : 'N/A',
    higherIsBetter: true,
  },
  'gender.wblIndex': {
    id: 'gender.wblIndex',
    name: "Women's Legal Rights",
    description: 'World Bank Women, Business and the Law Index (0-100)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },

  // === HEALTH & BODY ===
  'health.lifeExpectancy': {
    id: 'health.lifeExpectancy',
    name: 'Life Expectancy',
    description: 'Average life expectancy at birth (years)',
    category: 'health',
    type: 'numeric',
    domain: [40, 90],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'health.maleHeight': {
    id: 'health.maleHeight',
    name: 'Average Male Height',
    description: 'Average adult male height in centimeters',
    category: 'health',
    type: 'numeric',
    domain: [155, 185],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} cm` : 'N/A',
    higherIsBetter: true,
  },
  'health.obesityRate': {
    id: 'health.obesityRate',
    name: 'Obesity Rate',
    description: 'Percentage of adults with BMI ≥ 30',
    category: 'health',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'health.penisSize': {
    id: 'health.penisSize',
    name: 'Average Penis Size',
    description: 'Average erect penis length in centimeters',
    category: 'health',
    type: 'numeric',
    domain: [10, 18],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} cm` : 'N/A',
    higherIsBetter: true,
  },
  'health.fertilityRate': {
    id: 'health.fertilityRate',
    name: 'Fertility Rate',
    description: 'Average children per woman',
    category: 'health',
    type: 'numeric',
    domain: [1, 7],
    colorScheme: 'interpolateYlOrRd',
    format: (v) => v !== null ? `${(v as number).toFixed(2)} children` : 'N/A',
    higherIsBetter: true,
  },
  'health.alcoholConsumption': {
    id: 'health.alcoholConsumption',
    name: 'Alcohol Consumption',
    description: 'Liters of pure alcohol per capita per year',
    category: 'health',
    type: 'numeric',
    domain: [0, 15],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} L/year` : 'N/A',
    higherIsBetter: false,
  },
  'health.suicideRate': {
    id: 'health.suicideRate',
    name: 'Suicide Rate',
    description: 'Suicides per 100,000 population',
    category: 'health',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100k` : 'N/A',
    higherIsBetter: false,
  },

  // === SEX & RELATIONSHIPS ===
  'sex.sexualPartners': {
    id: 'sex.sexualPartners',
    name: 'Avg Sexual Partners',
    description: 'Average lifetime sexual partners',
    category: 'sex',
    type: 'numeric',
    domain: [0, 15],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} partners` : 'N/A',
    higherIsBetter: true,
  },
  'sex.divorceRate': {
    id: 'sex.divorceRate',
    name: 'Divorce Rate',
    description: 'Divorces per 1,000 people per year',
    category: 'sex',
    type: 'numeric',
    domain: [0, 5],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(2)} per 1k` : 'N/A',
    higherIsBetter: false,
  },
  'sex.lgbtAcceptance': {
    id: 'sex.lgbtAcceptance',
    name: 'LGBT+ Acceptance',
    description: 'Social acceptance of LGBT+ people (0-100)',
    category: 'sex',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateRainbow',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },

  // === DEMOGRAPHICS ===
  'demographics.ethnicDiversity': {
    id: 'demographics.ethnicDiversity',
    name: 'Ethnic Diversity',
    description: 'Ethnic fractionalization index (0=homogeneous, 1=diverse)',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolateSpectral',
    format: (v) => v !== null ? `${((v as number) * 100).toFixed(0)}%` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.medianAge': {
    id: 'demographics.medianAge',
    name: 'Median Age',
    description: 'Median age of population in years',
    category: 'demographics',
    type: 'numeric',
    domain: [15, 50],
    colorScheme: 'interpolateYlOrBr',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.urbanPopulation': {
    id: 'demographics.urbanPopulation',
    name: 'Urban Population',
    description: 'Percentage of population living in urban areas',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreys',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },

  // === INTELLIGENCE & EDUCATION ===
  'education.avgIQ': {
    id: 'education.avgIQ',
    name: 'Average IQ',
    description: 'National average IQ score',
    category: 'education',
    type: 'numeric',
    domain: [60, 110],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${Math.round(v as number)}` : 'N/A',
    higherIsBetter: true,
  },
  'education.literacyRate': {
    id: 'education.literacyRate',
    name: 'Literacy Rate',
    description: 'Percentage of adults who can read and write',
    category: 'education',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'education.pisaMath': {
    id: 'education.pisaMath',
    name: 'PISA Math Score',
    description: 'OECD PISA mathematics score',
    category: 'education',
    type: 'numeric',
    domain: [300, 600],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${Math.round(v as number)}` : 'N/A',
    higherIsBetter: true,
  },

  // === LIFESTYLE & HAPPINESS ===
  'lifestyle.happinessIndex': {
    id: 'lifestyle.happinessIndex',
    name: 'Happiness Index',
    description: 'World Happiness Report score (0-10)',
    category: 'lifestyle',
    type: 'numeric',
    domain: [2, 8],
    colorScheme: 'interpolateYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(2)}/10` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.workHoursWeek': {
    id: 'lifestyle.workHoursWeek',
    name: 'Work Hours/Week',
    description: 'Average working hours per week',
    category: 'lifestyle',
    type: 'numeric',
    domain: [25, 55],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} hrs` : 'N/A',
    higherIsBetter: false,
  },
  'lifestyle.internetPenetration': {
    id: 'lifestyle.internetPenetration',
    name: 'Internet Users',
    description: 'Percentage of population using the internet',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateCool',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.coffeeConsumption': {
    id: 'lifestyle.coffeeConsumption',
    name: 'Coffee Consumption',
    description: 'Kilograms of coffee per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 12],
    colorScheme: 'interpolateYlOrBr',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} kg/year` : 'N/A',
    higherIsBetter: true,
  },

  // === SAFETY & CRIME ===
  'crime.homicideRate': {
    id: 'crime.homicideRate',
    name: 'Homicide Rate',
    description: 'Intentional homicides per 100,000 population',
    category: 'safety',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100k` : 'N/A',
    higherIsBetter: false,
  },
  'crime.safetyIndex': {
    id: 'crime.safetyIndex',
    name: 'Safety Index',
    description: 'Safety index (0-100, higher is safer)',
    category: 'safety',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateYlGn',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'crime.gunOwnership': {
    id: 'crime.gunOwnership',
    name: 'Gun Ownership',
    description: 'Civilian firearms per 100 people',
    category: 'safety',
    type: 'numeric',
    domain: [0, 125],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100` : 'N/A',
    higherIsBetter: false,
  },
  'conflict.peaceIndex': {
    id: 'conflict.peaceIndex',
    name: 'Peace Index',
    description: 'Global Peace Index (1=most peaceful, 5=least peaceful)',
    category: 'safety',
    type: 'numeric',
    domain: [1, 5],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? (v as number).toFixed(2) : 'N/A',
    higherIsBetter: false,
  },

  // === RELIGION ===
  'religion.major': {
    id: 'religion.major',
    name: 'Major Religion',
    description: 'Predominant religion by population',
    category: 'religion',
    type: 'categorical',
    categories: [...MAJOR_RELIGIONS],
    colorScheme: 'schemeSet2',
    format: (v) => v as string || 'Unknown',
    higherIsBetter: true,
  },
}

export const DEFAULT_VARIABLE: ColorVariable = 'democracy.score'

export const DATA_SOURCES = {
  cia_factbook: {
    name: 'CIA World Factbook',
    url: 'https://www.cia.gov/the-world-factbook/',
    description: 'Comprehensive country information including demographics and religion',
  },
  vdem: {
    name: 'V-Dem Institute',
    url: 'https://v-dem.net/',
    description: 'Varieties of Democracy dataset measuring democracy indicators',
  },
  freedom_house: {
    name: 'Freedom House',
    url: 'https://freedomhouse.org/',
    description: 'Annual survey of political rights and civil liberties',
  },
  world_bank: {
    name: 'World Bank',
    url: 'https://data.worldbank.org/',
    description: 'Development indicators including poverty and gender equality',
  },
  ucdp: {
    name: 'Uppsala Conflict Data Program',
    url: 'https://ucdp.uu.se/',
    description: 'Armed conflict data since 1946',
  },
  gpi: {
    name: 'Global Peace Index',
    url: 'https://www.visionofhumanity.org/',
    description: 'Annual measure of national peacefulness',
  },
  who: {
    name: 'World Health Organization',
    url: 'https://www.who.int/data',
    description: 'Global health statistics and indicators',
  },
  oecd: {
    name: 'OECD',
    url: 'https://data.oecd.org/',
    description: 'Economic and social statistics for developed nations',
  },
  pisa: {
    name: 'OECD PISA',
    url: 'https://www.oecd.org/pisa/',
    description: 'Programme for International Student Assessment',
  },
  transparency: {
    name: 'Transparency International',
    url: 'https://www.transparency.org/',
    description: 'Corruption Perceptions Index',
  },
  happiness: {
    name: 'World Happiness Report',
    url: 'https://worldhappiness.report/',
    description: 'Annual survey of global happiness',
  },
  ncd_risc: {
    name: 'NCD Risk Factor Collaboration',
    url: 'https://ncdrisc.org/',
    description: 'Height, BMI, and other health metrics by country',
  },
  unodc: {
    name: 'UN Office on Drugs and Crime',
    url: 'https://dataunodc.un.org/',
    description: 'Crime and criminal justice statistics',
  },
  small_arms_survey: {
    name: 'Small Arms Survey',
    url: 'https://www.smallarmssurvey.org/',
    description: 'Civilian firearms ownership data',
  },
  world_population_review: {
    name: 'World Population Review',
    url: 'https://worldpopulationreview.com/',
    description: 'Demographics and various country statistics',
  },
  ilga: {
    name: 'ILGA World',
    url: 'https://ilga.org/',
    description: 'LGBT+ rights and acceptance data',
  },
}
