import type { VariableConfig, ColorVariable } from '@/types/country'

export const MAJOR_RELIGIONS = [
  'Christianity',
  'Islam',
  'Hinduism',
  'Buddhism',
  'Judaism',
  'Folk/Traditional',
  'Other',
  'None/Unaffiliated',
] as const

export const REGIONS = [
  'Africa',
  'Americas',
  'Asia',
  'Europe',
  'Oceania',
] as const

export const VARIABLE_CATEGORIES = [
  { id: 'governance', name: 'Governance & Freedom', icon: '🏛️' },
  { id: 'economy', name: 'Economy & Wealth', icon: '💰' },
  { id: 'health', name: 'Health & Body', icon: '🏥' },
  { id: 'sex', name: 'Sex & Relationships', icon: '❤️' },
  { id: 'demographics', name: 'Demographics', icon: '👥' },
  { id: 'education', name: 'Intelligence & Education', icon: '🎓' },
  { id: 'lifestyle', name: 'Lifestyle & Consumption', icon: '🍕' },
  { id: 'safety', name: 'Safety & Crime', icon: '🛡️' },
  { id: 'transport', name: 'Transport & Mobility', icon: '🚗' },
  { id: 'environment', name: 'Environment', icon: '🌍' },
  { id: 'religion', name: 'Religion', icon: '🙏' },
] as const

export const VARIABLES: Record<ColorVariable, VariableConfig> = {
  // === GOVERNANCE & FREEDOM ===
  'democracy.score': {
    id: 'democracy.score',
    name: 'Democracy Score',
    description: 'Combined democracy index (0-100) based on V-Dem and Freedom House data',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.corruptionIndex': {
    id: 'freedom.corruptionIndex',
    name: 'Corruption Index',
    description: 'Transparency International CPI (0=most corrupt, 100=cleanest)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.pressFreedom': {
    id: 'freedom.pressFreedom',
    name: 'Press Freedom',
    description: 'Reporters Without Borders index (0-100, higher = more free)',
    category: 'governance',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'freedom.cryptoAdoption': {
    id: 'freedom.cryptoAdoption',
    name: 'Crypto Adoption',
    description: 'Percentage of population using cryptocurrency',
    category: 'governance',
    type: 'numeric',
    domain: [0, 35],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },

  // === ECONOMY & WEALTH ===
  'poverty.gdpPerCapita': {
    id: 'poverty.gdpPerCapita',
    name: 'GDP per Capita',
    description: 'GDP per capita in USD (PPP)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100000],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `$${(v as number).toLocaleString()}` : 'N/A',
    higherIsBetter: true,
  },
  'poverty.hdi': {
    id: 'poverty.hdi',
    name: 'Human Development Index',
    description: 'UN Human Development Index (0-1)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? (v as number).toFixed(3) : 'N/A',
    higherIsBetter: true,
  },
  'gender.wblIndex': {
    id: 'gender.wblIndex',
    name: "Women's Legal Rights",
    description: 'World Bank Women, Business and the Law Index (0-100)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'economy.billionairesPerCapita': {
    id: 'economy.billionairesPerCapita',
    name: 'Billionaires per Capita',
    description: 'Number of billionaires per 10 million people',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 10M` : 'N/A',
    higherIsBetter: true,
  },
  'economy.millionairesPerCapita': {
    id: 'economy.millionairesPerCapita',
    name: 'Millionaires per Capita',
    description: 'Number of millionaires per 1,000 people',
    category: 'economy',
    type: 'numeric',
    domain: [0, 200],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'economy.startupUnicorns': {
    id: 'economy.startupUnicorns',
    name: 'Startup Unicorns',
    description: 'Number of $1B+ startups',
    category: 'economy',
    type: 'numeric',
    domain: [0, 500],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${Math.round(v as number)}` : 'N/A',
    higherIsBetter: true,
  },
  'economy.touristArrivals': {
    id: 'economy.touristArrivals',
    name: 'Tourist Arrivals',
    description: 'International tourists per 1,000 residents per year',
    category: 'economy',
    type: 'numeric',
    domain: [0, 5000],
    colorScheme: 'interpolateYlOrRd',
    format: (v) => v !== null ? `${Math.round(v as number)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'economy.mcdonaldsPerCapita': {
    id: 'economy.mcdonaldsPerCapita',
    name: "McDonald's per Capita",
    description: "McDonald's restaurants per million people",
    category: 'economy',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateYlOrRd',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1M` : 'N/A',
    higherIsBetter: true,
  },
  'economy.starbucksPerCapita': {
    id: 'economy.starbucksPerCapita',
    name: 'Starbucks per Capita',
    description: 'Starbucks stores per million people',
    category: 'economy',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1M` : 'N/A',
    higherIsBetter: true,
  },
  'economy.evAdoption': {
    id: 'economy.evAdoption',
    name: 'EV Adoption',
    description: 'Electric vehicles as % of new car sales',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.renewableEnergy': {
    id: 'economy.renewableEnergy',
    name: 'Renewable Energy',
    description: 'Percentage of electricity from renewable sources',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.debtToGdp': {
    id: 'economy.debtToGdp',
    name: 'Government Debt to GDP',
    description: 'Total government debt as percentage of GDP',
    category: 'economy',
    type: 'numeric',
    domain: [0, 250],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.gdpGrowth': {
    id: 'economy.gdpGrowth',
    name: 'GDP Growth Rate',
    description: 'Annual GDP growth rate (%)',
    category: 'economy',
    type: 'numeric',
    domain: [-10, 15],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.inflation': {
    id: 'economy.inflation',
    name: 'Inflation Rate',
    description: 'Annual inflation rate (Consumer Price Index)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.corporateTax': {
    id: 'economy.corporateTax',
    name: 'Corporate Tax Rate',
    description: 'Top statutory corporate income tax rate (%)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 55],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.incomeTax': {
    id: 'economy.incomeTax',
    name: 'Top Income Tax Rate',
    description: 'Top marginal personal income tax rate (%)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.vatRate': {
    id: 'economy.vatRate',
    name: 'VAT/Sales Tax Rate',
    description: 'Standard VAT or sales tax rate (%)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.unemploymentRate': {
    id: 'economy.unemploymentRate',
    name: 'Unemployment Rate',
    description: 'Percentage of labor force that is unemployed',
    category: 'economy',
    type: 'numeric',
    domain: [0, 35],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.youthUnemployment': {
    id: 'economy.youthUnemployment',
    name: 'Youth Unemployment Rate',
    description: 'Unemployment rate for ages 15-24 (%)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.fdiInflows': {
    id: 'economy.fdiInflows',
    name: 'FDI Inflows (% GDP)',
    description: 'Foreign direct investment net inflows as % of GDP',
    category: 'economy',
    type: 'numeric',
    domain: [-10, 50],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.tradeBalance': {
    id: 'economy.tradeBalance',
    name: 'Trade Balance (% GDP)',
    description: 'Net exports of goods and services as % of GDP',
    category: 'economy',
    type: 'numeric',
    domain: [-50, 50],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.exportsGdp': {
    id: 'economy.exportsGdp',
    name: 'Exports (% GDP)',
    description: 'Total exports as percentage of GDP',
    category: 'economy',
    type: 'numeric',
    domain: [0, 200],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.currentAccount': {
    id: 'economy.currentAccount',
    name: 'Current Account Balance',
    description: 'Current account balance as % of GDP',
    category: 'economy',
    type: 'numeric',
    domain: [-30, 30],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'economy.interestRate': {
    id: 'economy.interestRate',
    name: 'Central Bank Interest Rate',
    description: 'Policy interest rate set by central bank (%)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(2)}%` : 'N/A',
    higherIsBetter: false,
  },
  'economy.giniIndex': {
    id: 'economy.giniIndex',
    name: 'Gini Index (Inequality)',
    description: 'Income inequality coefficient (0=perfect equality, 100=max inequality)',
    category: 'economy',
    type: 'numeric',
    domain: [20, 70],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}` : 'N/A',
    higherIsBetter: false,
  },
  'economy.economicFreedom': {
    id: 'economy.economicFreedom',
    name: 'Economic Freedom Index',
    description: 'Heritage Foundation Index of Economic Freedom (0-100)',
    category: 'economy',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'economy.bigMacIndex': {
    id: 'economy.bigMacIndex',
    name: 'Big Mac Price (USD)',
    description: 'Price of a Big Mac in USD (purchasing power parity indicator)',
    category: 'economy',
    type: 'numeric',
    domain: [1, 10],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `$${(v as number).toFixed(2)}` : 'N/A',
    higherIsBetter: false,
  },

  // === HEALTH & BODY ===
  'health.lifeExpectancy': {
    id: 'health.lifeExpectancy',
    name: 'Life Expectancy',
    description: 'Average life expectancy at birth (years)',
    category: 'health',
    type: 'numeric',
    domain: [40, 90],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'health.maleHeight': {
    id: 'health.maleHeight',
    name: 'Average Male Height',
    description: 'Average adult male height in centimeters',
    category: 'health',
    type: 'numeric',
    domain: [155, 185],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} cm` : 'N/A',
    higherIsBetter: true,
  },
  'health.obesityRate': {
    id: 'health.obesityRate',
    name: 'Obesity Rate',
    description: 'Percentage of adults with BMI ≥ 30',
    category: 'health',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'health.penisSize': {
    id: 'health.penisSize',
    name: 'Average Penis Size',
    description: 'Average erect penis length in centimeters',
    category: 'health',
    type: 'numeric',
    domain: [10, 18],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} cm` : 'N/A',
    higherIsBetter: true,
  },
  'health.breastSize': {
    id: 'health.breastSize',
    name: 'Average Breast Size',
    description: 'Average breast cup size (1=AA, 2=A, 3=B, 4=C, 5=D)',
    category: 'health',
    type: 'numeric',
    domain: [1, 5],
    colorScheme: 'interpolatePuRd',
    format: (v) => {
      if (v === null) return 'N/A'
      const cups = ['', 'AA', 'A', 'B', 'C', 'D', 'DD']
      return cups[Math.round(v as number)] || `${(v as number).toFixed(1)}`
    },
    higherIsBetter: true,
  },
  'health.fertilityRate': {
    id: 'health.fertilityRate',
    name: 'Fertility Rate',
    description: 'Average children per woman',
    category: 'health',
    type: 'numeric',
    domain: [1, 7],
    colorScheme: 'interpolateYlOrRd',
    format: (v) => v !== null ? `${(v as number).toFixed(2)} children` : 'N/A',
    higherIsBetter: true,
  },
  'health.alcoholConsumption': {
    id: 'health.alcoholConsumption',
    name: 'Alcohol Consumption',
    description: 'Liters of pure alcohol per capita per year',
    category: 'health',
    type: 'numeric',
    domain: [0, 15],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} L/year` : 'N/A',
    higherIsBetter: false,
  },
  'health.suicideRate': {
    id: 'health.suicideRate',
    name: 'Suicide Rate',
    description: 'Suicides per 100,000 population',
    category: 'health',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100k` : 'N/A',
    higherIsBetter: false,
  },
  'health.hivPrevalence': {
    id: 'health.hivPrevalence',
    name: 'HIV Prevalence',
    description: 'HIV prevalence among adults 15-49 (%)',
    category: 'health',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'health.plasticSurgeryRate': {
    id: 'health.plasticSurgeryRate',
    name: 'Plastic Surgery Rate',
    description: 'Cosmetic procedures per 1,000 people',
    category: 'health',
    type: 'numeric',
    domain: [0, 15],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'health.sleepDuration': {
    id: 'health.sleepDuration',
    name: 'Sleep Duration',
    description: 'Average hours of sleep per night',
    category: 'health',
    type: 'numeric',
    domain: [6, 9],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} hrs` : 'N/A',
    higherIsBetter: true,
  },
  'health.diabetesRate': {
    id: 'health.diabetesRate',
    name: 'Diabetes Rate',
    description: 'Percentage of adults with diabetes',
    category: 'health',
    type: 'numeric',
    domain: [0, 35],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'health.airPollution': {
    id: 'health.airPollution',
    name: 'Air Pollution',
    description: 'PM2.5 concentration (μg/m³)',
    category: 'health',
    type: 'numeric',
    domain: [0, 80],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} μg/m³` : 'N/A',
    higherIsBetter: false,
  },

  // === SEX & RELATIONSHIPS ===
  'sex.sexualPartners': {
    id: 'sex.sexualPartners',
    name: 'Avg Sexual Partners',
    description: 'Average lifetime sexual partners',
    category: 'sex',
    type: 'numeric',
    domain: [0, 15],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} partners` : 'N/A',
    higherIsBetter: true,
  },
  'sex.ageFirstSex': {
    id: 'sex.ageFirstSex',
    name: 'Age of First Sex',
    description: 'Average age of first sexual intercourse',
    category: 'sex',
    type: 'numeric',
    domain: [15, 24],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'sex.divorceRate': {
    id: 'sex.divorceRate',
    name: 'Divorce Rate',
    description: 'Divorces per 1,000 people per year',
    category: 'sex',
    type: 'numeric',
    domain: [0, 5],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(2)} per 1k` : 'N/A',
    higherIsBetter: false,
  },
  'sex.lgbtAcceptance': {
    id: 'sex.lgbtAcceptance',
    name: 'LGBT+ Acceptance',
    description: 'Social acceptance of LGBT+ people (0-100)',
    category: 'sex',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateRainbow',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'sex.datingAppUsage': {
    id: 'sex.datingAppUsage',
    name: 'Dating App Usage',
    description: 'Percentage of adults using dating apps',
    category: 'sex',
    type: 'numeric',
    domain: [0, 35],
    colorScheme: 'interpolatePuRd',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'sex.onlyfansCreators': {
    id: 'sex.onlyfansCreators',
    name: 'OnlyFans Creators',
    description: 'OnlyFans creators per 100,000 people',
    category: 'sex',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100k` : 'N/A',
    higherIsBetter: true,
  },
  'sex.pornConsumption': {
    id: 'sex.pornConsumption',
    name: 'Porn Consumption',
    description: 'Average minutes of porn watched per week',
    category: 'sex',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${Math.round(v as number)} min/week` : 'N/A',
    higherIsBetter: true,
  },
  'sex.consanguinityRate': {
    id: 'sex.consanguinityRate',
    name: 'Consanguinity Rate',
    description: 'Percentage of marriages between blood relatives (cousin marriage)',
    category: 'sex',
    type: 'numeric',
    domain: [0, 70],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },

  // === DEMOGRAPHICS ===
  'demographics.ethnicDiversity': {
    id: 'demographics.ethnicDiversity',
    name: 'Ethnic Diversity',
    description: 'Ethnic fractionalization index (0=homogeneous, 1=diverse)',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 1],
    colorScheme: 'interpolateSpectral',
    format: (v) => v !== null ? `${((v as number) * 100).toFixed(0)}%` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.medianAge': {
    id: 'demographics.medianAge',
    name: 'Median Age',
    description: 'Median age of population in years',
    category: 'demographics',
    type: 'numeric',
    domain: [15, 50],
    colorScheme: 'interpolateYlOrBr',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} years` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.urbanPopulation': {
    id: 'demographics.urbanPopulation',
    name: 'Urban Population',
    description: 'Percentage of population living in urban areas',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreys',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.twinBirthRate': {
    id: 'demographics.twinBirthRate',
    name: 'Twin Birth Rate',
    description: 'Twin births per 1,000 births',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.immigrationRate': {
    id: 'demographics.immigrationRate',
    name: 'Immigration Rate',
    description: 'Percentage of population that is foreign-born (legal immigrants)',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 90],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.illegalImmigrationRate': {
    id: 'demographics.illegalImmigrationRate',
    name: 'Illegal Immigration Rate',
    description: 'Estimated percentage of population that are unauthorized immigrants',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 25],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: false,
  },
  'demographics.netMigrationRate': {
    id: 'demographics.netMigrationRate',
    name: 'Net Migration Rate',
    description: 'Net migrants per 1,000 population per year (positive = immigration)',
    category: 'demographics',
    type: 'numeric',
    domain: [-30, 20],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'demographics.refugeesHosted': {
    id: 'demographics.refugeesHosted',
    name: 'Refugees Hosted',
    description: 'Refugees per 1,000 population',
    category: 'demographics',
    type: 'numeric',
    domain: [0, 150],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 1k` : 'N/A',
    higherIsBetter: true,
  },

  // === INTELLIGENCE & EDUCATION ===
  'education.avgIQ': {
    id: 'education.avgIQ',
    name: 'Average IQ',
    description: 'National average IQ score',
    category: 'education',
    type: 'numeric',
    domain: [60, 110],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${Math.round(v as number)}` : 'N/A',
    higherIsBetter: true,
  },
  'education.literacyRate': {
    id: 'education.literacyRate',
    name: 'Literacy Rate',
    description: 'Percentage of adults who can read and write',
    category: 'education',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'education.pisaMath': {
    id: 'education.pisaMath',
    name: 'PISA Math Score',
    description: 'OECD PISA mathematics score',
    category: 'education',
    type: 'numeric',
    domain: [300, 600],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${Math.round(v as number)}` : 'N/A',
    higherIsBetter: true,
  },
  'education.nobelPrizesPerCapita': {
    id: 'education.nobelPrizesPerCapita',
    name: 'Nobel Prizes per Capita',
    description: 'Nobel Prize winners per 10 million people',
    category: 'education',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolateGolds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 10M` : 'N/A',
    higherIsBetter: true,
  },
  'education.chessGrandmasters': {
    id: 'education.chessGrandmasters',
    name: 'Chess Grandmasters',
    description: 'Chess grandmasters per 10 million people',
    category: 'education',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 10M` : 'N/A',
    higherIsBetter: true,
  },
  'education.englishProficiency': {
    id: 'education.englishProficiency',
    name: 'English Proficiency',
    description: 'EF English Proficiency Index (0-100)',
    category: 'education',
    type: 'numeric',
    domain: [40, 90],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },

  // === LIFESTYLE & CONSUMPTION ===
  'lifestyle.happinessIndex': {
    id: 'lifestyle.happinessIndex',
    name: 'Happiness Index',
    description: 'World Happiness Report score (0-10)',
    category: 'lifestyle',
    type: 'numeric',
    domain: [2, 8],
    colorScheme: 'interpolateYlGn',
    format: (v) => v !== null ? `${(v as number).toFixed(2)}/10` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.workHoursWeek': {
    id: 'lifestyle.workHoursWeek',
    name: 'Work Hours/Week',
    description: 'Average working hours per week',
    category: 'lifestyle',
    type: 'numeric',
    domain: [25, 55],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} hrs` : 'N/A',
    higherIsBetter: false,
  },
  'lifestyle.internetPenetration': {
    id: 'lifestyle.internetPenetration',
    name: 'Internet Users',
    description: 'Percentage of population using the internet',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateCool',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.coffeeConsumption': {
    id: 'lifestyle.coffeeConsumption',
    name: 'Coffee Consumption',
    description: 'Kilograms of coffee per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 12],
    colorScheme: 'interpolateYlOrBr',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} kg/year` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.screenTime': {
    id: 'lifestyle.screenTime',
    name: 'Screen Time',
    description: 'Average hours per day on screens',
    category: 'lifestyle',
    type: 'numeric',
    domain: [4, 12],
    colorScheme: 'interpolateBlues',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} hrs/day` : 'N/A',
    higherIsBetter: false,
  },
  'lifestyle.videoGamePlayers': {
    id: 'lifestyle.videoGamePlayers',
    name: 'Video Game Players',
    description: 'Percentage of population playing video games',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 80],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.tattooRate': {
    id: 'lifestyle.tattooRate',
    name: 'Tattoo Rate',
    description: 'Percentage of adults with at least one tattoo',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateGreys',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.pizzaConsumption': {
    id: 'lifestyle.pizzaConsumption',
    name: 'Pizza Consumption',
    description: 'Kilograms of pizza per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 12],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} kg/year` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.chocolateConsumption': {
    id: 'lifestyle.chocolateConsumption',
    name: 'Chocolate Consumption',
    description: 'Kilograms of chocolate per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 10],
    colorScheme: 'interpolateYlOrBr',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} kg/year` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.teaConsumption': {
    id: 'lifestyle.teaConsumption',
    name: 'Tea Consumption',
    description: 'Kilograms of tea per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 4],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(2)} kg/year` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.beerConsumption': {
    id: 'lifestyle.beerConsumption',
    name: 'Beer Consumption',
    description: 'Liters of beer per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 200],
    colorScheme: 'interpolateYlOrRd',
    format: (v) => v !== null ? `${Math.round(v as number)} L/year` : 'N/A',
    higherIsBetter: true,
  },
  'lifestyle.wineConsumption': {
    id: 'lifestyle.wineConsumption',
    name: 'Wine Consumption',
    description: 'Liters of wine per capita per year',
    category: 'lifestyle',
    type: 'numeric',
    domain: [0, 60],
    colorScheme: 'interpolatePurples',
    format: (v) => v !== null ? `${Math.round(v as number)} L/year` : 'N/A',
    higherIsBetter: true,
  },

  // === SAFETY & CRIME ===
  'crime.homicideRate': {
    id: 'crime.homicideRate',
    name: 'Homicide Rate',
    description: 'Intentional homicides per 100,000 population',
    category: 'safety',
    type: 'numeric',
    domain: [0, 50],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100k` : 'N/A',
    higherIsBetter: false,
  },
  'crime.safetyIndex': {
    id: 'crime.safetyIndex',
    name: 'Safety Index',
    description: 'Safety index (0-100, higher is safer)',
    category: 'safety',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateYlGn',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: true,
  },
  'crime.gunOwnership': {
    id: 'crime.gunOwnership',
    name: 'Gun Ownership',
    description: 'Civilian firearms per 100 people',
    category: 'safety',
    type: 'numeric',
    domain: [0, 125],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} per 100` : 'N/A',
    higherIsBetter: false,
  },
  'conflict.peaceIndex': {
    id: 'conflict.peaceIndex',
    name: 'Peace Index',
    description: 'Global Peace Index (1=most peaceful, 5=least peaceful)',
    category: 'safety',
    type: 'numeric',
    domain: [1, 5],
    colorScheme: 'interpolateRdYlGn',
    format: (v) => v !== null ? (v as number).toFixed(2) : 'N/A',
    higherIsBetter: false,
  },

  // === TRANSPORT & MOBILITY ===
  'transport.carOwnership': {
    id: 'transport.carOwnership',
    name: 'Car Ownership',
    description: 'Vehicles per 1,000 people',
    category: 'transport',
    type: 'numeric',
    domain: [0, 900],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${Math.round(v as number)} per 1k` : 'N/A',
    higherIsBetter: true,
  },
  'transport.bicycleUsage': {
    id: 'transport.bicycleUsage',
    name: 'Bicycle Usage',
    description: 'Percentage of commuters using bicycles',
    category: 'transport',
    type: 'numeric',
    domain: [0, 30],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'transport.averageCommute': {
    id: 'transport.averageCommute',
    name: 'Average Commute',
    description: 'Average commute time (minutes one-way)',
    category: 'transport',
    type: 'numeric',
    domain: [20, 60],
    colorScheme: 'interpolateOranges',
    format: (v) => v !== null ? `${Math.round(v as number)} min` : 'N/A',
    higherIsBetter: false,
  },
  'transport.trafficIndex': {
    id: 'transport.trafficIndex',
    name: 'Traffic Index',
    description: 'Traffic congestion index (0-100)',
    category: 'transport',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${Math.round(v as number)}/100` : 'N/A',
    higherIsBetter: false,
  },

  // === ENVIRONMENT ===
  'environment.co2PerCapita': {
    id: 'environment.co2PerCapita',
    name: 'CO2 per Capita',
    description: 'Carbon dioxide emissions (tonnes per person per year)',
    category: 'environment',
    type: 'numeric',
    domain: [0, 35],
    colorScheme: 'interpolateReds',
    format: (v) => v !== null ? `${(v as number).toFixed(1)} tonnes` : 'N/A',
    higherIsBetter: false,
  },
  'environment.recyclingRate': {
    id: 'environment.recyclingRate',
    name: 'Recycling Rate',
    description: 'Percentage of waste recycled',
    category: 'environment',
    type: 'numeric',
    domain: [0, 70],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },
  'environment.forestCoverage': {
    id: 'environment.forestCoverage',
    name: 'Forest Coverage',
    description: 'Percentage of land area covered by forest',
    category: 'environment',
    type: 'numeric',
    domain: [0, 100],
    colorScheme: 'interpolateGreens',
    format: (v) => v !== null ? `${(v as number).toFixed(1)}%` : 'N/A',
    higherIsBetter: true,
  },

  // === RELIGION ===
  'religion.major': {
    id: 'religion.major',
    name: 'Major Religion',
    description: 'Predominant religion by population',
    category: 'religion',
    type: 'categorical',
    categories: [...MAJOR_RELIGIONS],
    colorScheme: 'schemeSet2',
    format: (v) => v as string || 'Unknown',
    higherIsBetter: true,
  },
}

export const DEFAULT_VARIABLE: ColorVariable = 'democracy.score'

export const DATA_SOURCES = {
  cia_factbook: {
    name: 'CIA World Factbook',
    url: 'https://www.cia.gov/the-world-factbook/',
    description: 'Comprehensive country information including demographics and religion',
  },
  vdem: {
    name: 'V-Dem Institute',
    url: 'https://v-dem.net/',
    description: 'Varieties of Democracy dataset measuring democracy indicators',
  },
  freedom_house: {
    name: 'Freedom House',
    url: 'https://freedomhouse.org/',
    description: 'Annual survey of political rights and civil liberties',
  },
  world_bank: {
    name: 'World Bank',
    url: 'https://data.worldbank.org/',
    description: 'Development indicators including poverty and gender equality',
  },
  ucdp: {
    name: 'Uppsala Conflict Data Program',
    url: 'https://ucdp.uu.se/',
    description: 'Armed conflict data since 1946',
  },
  gpi: {
    name: 'Global Peace Index',
    url: 'https://www.visionofhumanity.org/',
    description: 'Annual measure of national peacefulness',
  },
  who: {
    name: 'World Health Organization',
    url: 'https://www.who.int/data',
    description: 'Global health statistics and indicators',
  },
  oecd: {
    name: 'OECD',
    url: 'https://data.oecd.org/',
    description: 'Economic and social statistics for developed nations',
  },
  pisa: {
    name: 'OECD PISA',
    url: 'https://www.oecd.org/pisa/',
    description: 'Programme for International Student Assessment',
  },
  transparency: {
    name: 'Transparency International',
    url: 'https://www.transparency.org/',
    description: 'Corruption Perceptions Index',
  },
  happiness: {
    name: 'World Happiness Report',
    url: 'https://worldhappiness.report/',
    description: 'Annual survey of global happiness',
  },
  ncd_risc: {
    name: 'NCD Risk Factor Collaboration',
    url: 'https://ncdrisc.org/',
    description: 'Height, BMI, and other health metrics by country',
  },
  unodc: {
    name: 'UN Office on Drugs and Crime',
    url: 'https://dataunodc.un.org/',
    description: 'Crime and criminal justice statistics',
  },
  small_arms_survey: {
    name: 'Small Arms Survey',
    url: 'https://www.smallarmssurvey.org/',
    description: 'Civilian firearms ownership data',
  },
  world_population_review: {
    name: 'World Population Review',
    url: 'https://worldpopulationreview.com/',
    description: 'Demographics and various country statistics',
  },
  ilga: {
    name: 'ILGA World',
    url: 'https://ilga.org/',
    description: 'LGBT+ rights and acceptance data',
  },
}
