/**
 * Data fetching script - collects country data from multiple sources
 * Run with: npm run fetch-data
 */

import * as fs from 'fs'
import * as path from 'path'

const OUTPUT_PATH = path.join(__dirname, '../data/countries.json')

// ISO3 country codes mapping
const COUNTRY_CODES: Record<string, { iso2: string; name: string; region: string; subregion: string }> = {
  AFG: { iso2: 'AF', name: 'Afghanistan', region: 'Asia', subregion: 'Southern Asia' },
  ALB: { iso2: 'AL', name: 'Albania', region: 'Europe', subregion: 'Southern Europe' },
  DZA: { iso2: 'DZ', name: 'Algeria', region: 'Africa', subregion: 'Northern Africa' },
  AND: { iso2: 'AD', name: 'Andorra', region: 'Europe', subregion: 'Southern Europe' },
  AGO: { iso2: 'AO', name: 'Angola', region: 'Africa', subregion: 'Middle Africa' },
  ARG: { iso2: 'AR', name: 'Argentina', region: 'Americas', subregion: 'South America' },
  ARM: { iso2: 'AM', name: 'Armenia', region: 'Asia', subregion: 'Western Asia' },
  AUS: { iso2: 'AU', name: 'Australia', region: 'Oceania', subregion: 'Australia and New Zealand' },
  AUT: { iso2: 'AT', name: 'Austria', region: 'Europe', subregion: 'Western Europe' },
  AZE: { iso2: 'AZ', name: 'Azerbaijan', region: 'Asia', subregion: 'Western Asia' },
  BHR: { iso2: 'BH', name: 'Bahrain', region: 'Asia', subregion: 'Western Asia' },
  BGD: { iso2: 'BD', name: 'Bangladesh', region: 'Asia', subregion: 'Southern Asia' },
  BLR: { iso2: 'BY', name: 'Belarus', region: 'Europe', subregion: 'Eastern Europe' },
  BEL: { iso2: 'BE', name: 'Belgium', region: 'Europe', subregion: 'Western Europe' },
  BEN: { iso2: 'BJ', name: 'Benin', region: 'Africa', subregion: 'Western Africa' },
  BTN: { iso2: 'BT', name: 'Bhutan', region: 'Asia', subregion: 'Southern Asia' },
  BOL: { iso2: 'BO', name: 'Bolivia', region: 'Americas', subregion: 'South America' },
  BIH: { iso2: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe', subregion: 'Southern Europe' },
  BWA: { iso2: 'BW', name: 'Botswana', region: 'Africa', subregion: 'Southern Africa' },
  BRA: { iso2: 'BR', name: 'Brazil', region: 'Americas', subregion: 'South America' },
  BRN: { iso2: 'BN', name: 'Brunei', region: 'Asia', subregion: 'South-Eastern Asia' },
  BGR: { iso2: 'BG', name: 'Bulgaria', region: 'Europe', subregion: 'Eastern Europe' },
  BFA: { iso2: 'BF', name: 'Burkina Faso', region: 'Africa', subregion: 'Western Africa' },
  BDI: { iso2: 'BI', name: 'Burundi', region: 'Africa', subregion: 'Eastern Africa' },
  KHM: { iso2: 'KH', name: 'Cambodia', region: 'Asia', subregion: 'South-Eastern Asia' },
  CMR: { iso2: 'CM', name: 'Cameroon', region: 'Africa', subregion: 'Middle Africa' },
  CAN: { iso2: 'CA', name: 'Canada', region: 'Americas', subregion: 'Northern America' },
  CAF: { iso2: 'CF', name: 'Central African Republic', region: 'Africa', subregion: 'Middle Africa' },
  TCD: { iso2: 'TD', name: 'Chad', region: 'Africa', subregion: 'Middle Africa' },
  CHL: { iso2: 'CL', name: 'Chile', region: 'Americas', subregion: 'South America' },
  CHN: { iso2: 'CN', name: 'China', region: 'Asia', subregion: 'Eastern Asia' },
  COL: { iso2: 'CO', name: 'Colombia', region: 'Americas', subregion: 'South America' },
  COD: { iso2: 'CD', name: 'DR Congo', region: 'Africa', subregion: 'Middle Africa' },
  COG: { iso2: 'CG', name: 'Congo', region: 'Africa', subregion: 'Middle Africa' },
  CRI: { iso2: 'CR', name: 'Costa Rica', region: 'Americas', subregion: 'Central America' },
  CIV: { iso2: 'CI', name: "Cote d'Ivoire", region: 'Africa', subregion: 'Western Africa' },
  HRV: { iso2: 'HR', name: 'Croatia', region: 'Europe', subregion: 'Southern Europe' },
  CUB: { iso2: 'CU', name: 'Cuba', region: 'Americas', subregion: 'Caribbean' },
  CYP: { iso2: 'CY', name: 'Cyprus', region: 'Europe', subregion: 'Southern Europe' },
  CZE: { iso2: 'CZ', name: 'Czechia', region: 'Europe', subregion: 'Eastern Europe' },
  DNK: { iso2: 'DK', name: 'Denmark', region: 'Europe', subregion: 'Northern Europe' },
  DJI: { iso2: 'DJ', name: 'Djibouti', region: 'Africa', subregion: 'Eastern Africa' },
  DOM: { iso2: 'DO', name: 'Dominican Republic', region: 'Americas', subregion: 'Caribbean' },
  ECU: { iso2: 'EC', name: 'Ecuador', region: 'Americas', subregion: 'South America' },
  EGY: { iso2: 'EG', name: 'Egypt', region: 'Africa', subregion: 'Northern Africa' },
  SLV: { iso2: 'SV', name: 'El Salvador', region: 'Americas', subregion: 'Central America' },
  GNQ: { iso2: 'GQ', name: 'Equatorial Guinea', region: 'Africa', subregion: 'Middle Africa' },
  ERI: { iso2: 'ER', name: 'Eritrea', region: 'Africa', subregion: 'Eastern Africa' },
  EST: { iso2: 'EE', name: 'Estonia', region: 'Europe', subregion: 'Northern Europe' },
  SWZ: { iso2: 'SZ', name: 'Eswatini', region: 'Africa', subregion: 'Southern Africa' },
  ETH: { iso2: 'ET', name: 'Ethiopia', region: 'Africa', subregion: 'Eastern Africa' },
  FIN: { iso2: 'FI', name: 'Finland', region: 'Europe', subregion: 'Northern Europe' },
  FRA: { iso2: 'FR', name: 'France', region: 'Europe', subregion: 'Western Europe' },
  GAB: { iso2: 'GA', name: 'Gabon', region: 'Africa', subregion: 'Middle Africa' },
  GMB: { iso2: 'GM', name: 'Gambia', region: 'Africa', subregion: 'Western Africa' },
  GEO: { iso2: 'GE', name: 'Georgia', region: 'Asia', subregion: 'Western Asia' },
  DEU: { iso2: 'DE', name: 'Germany', region: 'Europe', subregion: 'Western Europe' },
  GHA: { iso2: 'GH', name: 'Ghana', region: 'Africa', subregion: 'Western Africa' },
  GRC: { iso2: 'GR', name: 'Greece', region: 'Europe', subregion: 'Southern Europe' },
  GTM: { iso2: 'GT', name: 'Guatemala', region: 'Americas', subregion: 'Central America' },
  GIN: { iso2: 'GN', name: 'Guinea', region: 'Africa', subregion: 'Western Africa' },
  GNB: { iso2: 'GW', name: 'Guinea-Bissau', region: 'Africa', subregion: 'Western Africa' },
  GUY: { iso2: 'GY', name: 'Guyana', region: 'Americas', subregion: 'South America' },
  HTI: { iso2: 'HT', name: 'Haiti', region: 'Americas', subregion: 'Caribbean' },
  HND: { iso2: 'HN', name: 'Honduras', region: 'Americas', subregion: 'Central America' },
  HUN: { iso2: 'HU', name: 'Hungary', region: 'Europe', subregion: 'Eastern Europe' },
  ISL: { iso2: 'IS', name: 'Iceland', region: 'Europe', subregion: 'Northern Europe' },
  IND: { iso2: 'IN', name: 'India', region: 'Asia', subregion: 'Southern Asia' },
  IDN: { iso2: 'ID', name: 'Indonesia', region: 'Asia', subregion: 'South-Eastern Asia' },
  IRN: { iso2: 'IR', name: 'Iran', region: 'Asia', subregion: 'Southern Asia' },
  IRQ: { iso2: 'IQ', name: 'Iraq', region: 'Asia', subregion: 'Western Asia' },
  IRL: { iso2: 'IE', name: 'Ireland', region: 'Europe', subregion: 'Northern Europe' },
  ISR: { iso2: 'IL', name: 'Israel', region: 'Asia', subregion: 'Western Asia' },
  ITA: { iso2: 'IT', name: 'Italy', region: 'Europe', subregion: 'Southern Europe' },
  JAM: { iso2: 'JM', name: 'Jamaica', region: 'Americas', subregion: 'Caribbean' },
  JPN: { iso2: 'JP', name: 'Japan', region: 'Asia', subregion: 'Eastern Asia' },
  JOR: { iso2: 'JO', name: 'Jordan', region: 'Asia', subregion: 'Western Asia' },
  KAZ: { iso2: 'KZ', name: 'Kazakhstan', region: 'Asia', subregion: 'Central Asia' },
  KEN: { iso2: 'KE', name: 'Kenya', region: 'Africa', subregion: 'Eastern Africa' },
  PRK: { iso2: 'KP', name: 'North Korea', region: 'Asia', subregion: 'Eastern Asia' },
  KOR: { iso2: 'KR', name: 'South Korea', region: 'Asia', subregion: 'Eastern Asia' },
  KWT: { iso2: 'KW', name: 'Kuwait', region: 'Asia', subregion: 'Western Asia' },
  KGZ: { iso2: 'KG', name: 'Kyrgyzstan', region: 'Asia', subregion: 'Central Asia' },
  LAO: { iso2: 'LA', name: 'Laos', region: 'Asia', subregion: 'South-Eastern Asia' },
  LVA: { iso2: 'LV', name: 'Latvia', region: 'Europe', subregion: 'Northern Europe' },
  LBN: { iso2: 'LB', name: 'Lebanon', region: 'Asia', subregion: 'Western Asia' },
  LSO: { iso2: 'LS', name: 'Lesotho', region: 'Africa', subregion: 'Southern Africa' },
  LBR: { iso2: 'LR', name: 'Liberia', region: 'Africa', subregion: 'Western Africa' },
  LBY: { iso2: 'LY', name: 'Libya', region: 'Africa', subregion: 'Northern Africa' },
  LTU: { iso2: 'LT', name: 'Lithuania', region: 'Europe', subregion: 'Northern Europe' },
  LUX: { iso2: 'LU', name: 'Luxembourg', region: 'Europe', subregion: 'Western Europe' },
  MDG: { iso2: 'MG', name: 'Madagascar', region: 'Africa', subregion: 'Eastern Africa' },
  MWI: { iso2: 'MW', name: 'Malawi', region: 'Africa', subregion: 'Eastern Africa' },
  MYS: { iso2: 'MY', name: 'Malaysia', region: 'Asia', subregion: 'South-Eastern Asia' },
  MLI: { iso2: 'ML', name: 'Mali', region: 'Africa', subregion: 'Western Africa' },
  MRT: { iso2: 'MR', name: 'Mauritania', region: 'Africa', subregion: 'Western Africa' },
  MUS: { iso2: 'MU', name: 'Mauritius', region: 'Africa', subregion: 'Eastern Africa' },
  MEX: { iso2: 'MX', name: 'Mexico', region: 'Americas', subregion: 'Central America' },
  MDA: { iso2: 'MD', name: 'Moldova', region: 'Europe', subregion: 'Eastern Europe' },
  MNG: { iso2: 'MN', name: 'Mongolia', region: 'Asia', subregion: 'Eastern Asia' },
  MNE: { iso2: 'ME', name: 'Montenegro', region: 'Europe', subregion: 'Southern Europe' },
  MAR: { iso2: 'MA', name: 'Morocco', region: 'Africa', subregion: 'Northern Africa' },
  MOZ: { iso2: 'MZ', name: 'Mozambique', region: 'Africa', subregion: 'Eastern Africa' },
  MMR: { iso2: 'MM', name: 'Myanmar', region: 'Asia', subregion: 'South-Eastern Asia' },
  NAM: { iso2: 'NA', name: 'Namibia', region: 'Africa', subregion: 'Southern Africa' },
  NPL: { iso2: 'NP', name: 'Nepal', region: 'Asia', subregion: 'Southern Asia' },
  NLD: { iso2: 'NL', name: 'Netherlands', region: 'Europe', subregion: 'Western Europe' },
  NZL: { iso2: 'NZ', name: 'New Zealand', region: 'Oceania', subregion: 'Australia and New Zealand' },
  NIC: { iso2: 'NI', name: 'Nicaragua', region: 'Americas', subregion: 'Central America' },
  NER: { iso2: 'NE', name: 'Niger', region: 'Africa', subregion: 'Western Africa' },
  NGA: { iso2: 'NG', name: 'Nigeria', region: 'Africa', subregion: 'Western Africa' },
  NOR: { iso2: 'NO', name: 'Norway', region: 'Europe', subregion: 'Northern Europe' },
  OMN: { iso2: 'OM', name: 'Oman', region: 'Asia', subregion: 'Western Asia' },
  PAK: { iso2: 'PK', name: 'Pakistan', region: 'Asia', subregion: 'Southern Asia' },
  PAN: { iso2: 'PA', name: 'Panama', region: 'Americas', subregion: 'Central America' },
  PNG: { iso2: 'PG', name: 'Papua New Guinea', region: 'Oceania', subregion: 'Melanesia' },
  PRY: { iso2: 'PY', name: 'Paraguay', region: 'Americas', subregion: 'South America' },
  PER: { iso2: 'PE', name: 'Peru', region: 'Americas', subregion: 'South America' },
  PHL: { iso2: 'PH', name: 'Philippines', region: 'Asia', subregion: 'South-Eastern Asia' },
  POL: { iso2: 'PL', name: 'Poland', region: 'Europe', subregion: 'Eastern Europe' },
  PRT: { iso2: 'PT', name: 'Portugal', region: 'Europe', subregion: 'Southern Europe' },
  QAT: { iso2: 'QA', name: 'Qatar', region: 'Asia', subregion: 'Western Asia' },
  ROU: { iso2: 'RO', name: 'Romania', region: 'Europe', subregion: 'Eastern Europe' },
  RUS: { iso2: 'RU', name: 'Russia', region: 'Europe', subregion: 'Eastern Europe' },
  RWA: { iso2: 'RW', name: 'Rwanda', region: 'Africa', subregion: 'Eastern Africa' },
  SAU: { iso2: 'SA', name: 'Saudi Arabia', region: 'Asia', subregion: 'Western Asia' },
  SEN: { iso2: 'SN', name: 'Senegal', region: 'Africa', subregion: 'Western Africa' },
  SRB: { iso2: 'RS', name: 'Serbia', region: 'Europe', subregion: 'Southern Europe' },
  SLE: { iso2: 'SL', name: 'Sierra Leone', region: 'Africa', subregion: 'Western Africa' },
  SGP: { iso2: 'SG', name: 'Singapore', region: 'Asia', subregion: 'South-Eastern Asia' },
  SVK: { iso2: 'SK', name: 'Slovakia', region: 'Europe', subregion: 'Eastern Europe' },
  SVN: { iso2: 'SI', name: 'Slovenia', region: 'Europe', subregion: 'Southern Europe' },
  SOM: { iso2: 'SO', name: 'Somalia', region: 'Africa', subregion: 'Eastern Africa' },
  ZAF: { iso2: 'ZA', name: 'South Africa', region: 'Africa', subregion: 'Southern Africa' },
  SSD: { iso2: 'SS', name: 'South Sudan', region: 'Africa', subregion: 'Eastern Africa' },
  ESP: { iso2: 'ES', name: 'Spain', region: 'Europe', subregion: 'Southern Europe' },
  LKA: { iso2: 'LK', name: 'Sri Lanka', region: 'Asia', subregion: 'Southern Asia' },
  SDN: { iso2: 'SD', name: 'Sudan', region: 'Africa', subregion: 'Northern Africa' },
  SUR: { iso2: 'SR', name: 'Suriname', region: 'Americas', subregion: 'South America' },
  SWE: { iso2: 'SE', name: 'Sweden', region: 'Europe', subregion: 'Northern Europe' },
  CHE: { iso2: 'CH', name: 'Switzerland', region: 'Europe', subregion: 'Western Europe' },
  SYR: { iso2: 'SY', name: 'Syria', region: 'Asia', subregion: 'Western Asia' },
  TWN: { iso2: 'TW', name: 'Taiwan', region: 'Asia', subregion: 'Eastern Asia' },
  TJK: { iso2: 'TJ', name: 'Tajikistan', region: 'Asia', subregion: 'Central Asia' },
  TZA: { iso2: 'TZ', name: 'Tanzania', region: 'Africa', subregion: 'Eastern Africa' },
  THA: { iso2: 'TH', name: 'Thailand', region: 'Asia', subregion: 'South-Eastern Asia' },
  TLS: { iso2: 'TL', name: 'Timor-Leste', region: 'Asia', subregion: 'South-Eastern Asia' },
  TGO: { iso2: 'TG', name: 'Togo', region: 'Africa', subregion: 'Western Africa' },
  TTO: { iso2: 'TT', name: 'Trinidad and Tobago', region: 'Americas', subregion: 'Caribbean' },
  TUN: { iso2: 'TN', name: 'Tunisia', region: 'Africa', subregion: 'Northern Africa' },
  TUR: { iso2: 'TR', name: 'Turkey', region: 'Asia', subregion: 'Western Asia' },
  TKM: { iso2: 'TM', name: 'Turkmenistan', region: 'Asia', subregion: 'Central Asia' },
  UGA: { iso2: 'UG', name: 'Uganda', region: 'Africa', subregion: 'Eastern Africa' },
  UKR: { iso2: 'UA', name: 'Ukraine', region: 'Europe', subregion: 'Eastern Europe' },
  ARE: { iso2: 'AE', name: 'United Arab Emirates', region: 'Asia', subregion: 'Western Asia' },
  GBR: { iso2: 'GB', name: 'United Kingdom', region: 'Europe', subregion: 'Northern Europe' },
  USA: { iso2: 'US', name: 'United States', region: 'Americas', subregion: 'Northern America' },
  URY: { iso2: 'UY', name: 'Uruguay', region: 'Americas', subregion: 'South America' },
  UZB: { iso2: 'UZ', name: 'Uzbekistan', region: 'Asia', subregion: 'Central Asia' },
  VEN: { iso2: 'VE', name: 'Venezuela', region: 'Americas', subregion: 'South America' },
  VNM: { iso2: 'VN', name: 'Vietnam', region: 'Asia', subregion: 'South-Eastern Asia' },
  YEM: { iso2: 'YE', name: 'Yemen', region: 'Asia', subregion: 'Western Asia' },
  ZMB: { iso2: 'ZM', name: 'Zambia', region: 'Africa', subregion: 'Eastern Africa' },
  ZWE: { iso2: 'ZW', name: 'Zimbabwe', region: 'Africa', subregion: 'Eastern Africa' },
}

async function fetchJson(url: string) {
  const response = await fetch(url)
  if (!response.ok) throw new Error(`HTTP ${response.status}: ${url}`)
  return response.json()
}

async function fetchWorldBankIndicator(indicator: string): Promise<Record<string, number>> {
  const url = `https://api.worldbank.org/v2/country/all/indicator/${indicator}?format=json&per_page=300&mrv=1`
  try {
    const data = await fetchJson(url)
    const result: Record<string, number> = {}
    if (data[1]) {
      for (const item of data[1]) {
        if (item.value !== null && item.countryiso3code) {
          result[item.countryiso3code] = item.value
        }
      }
    }
    return result
  } catch (e) {
    console.error(`Failed to fetch ${indicator}:`, e)
    return {}
  }
}

async function main() {
  console.log('Fetching country data from multiple sources...\n')

  // Fetch World Bank indicators
  console.log('Fetching World Bank data...')
  const [gdpData, povertyData, genderData, hdiData] = await Promise.all([
    fetchWorldBankIndicator('NY.GDP.PCAP.PP.CD'), // GDP per capita PPP
    fetchWorldBankIndicator('SI.POV.DDAY'),       // Poverty headcount
    fetchWorldBankIndicator('SG.LAW.INDX'),       // Women Business Law
    fetchWorldBankIndicator('HD.HCI.OVRL'),       // Human Capital Index (proxy for HDI)
  ])

  console.log(`  GDP data: ${Object.keys(gdpData).length} countries`)
  console.log(`  Poverty data: ${Object.keys(povertyData).length} countries`)
  console.log(`  Gender data: ${Object.keys(genderData).length} countries`)

  // Build country array with all data
  const countries = Object.entries(COUNTRY_CODES).map(([iso3, info]) => {
    // Get religion data (hardcoded from major sources)
    const religionData = RELIGION_DATA[iso3] || { major: 'Unknown', breakdown: {} }

    // Get democracy data (hardcoded from V-Dem/Freedom House)
    const democracyInfo = DEMOCRACY_DATA[iso3] || { score: 50, freedomScore: null, vdemScore: null }

    // Get conflict data (hardcoded from UCDP/GPI)
    const conflictInfo = CONFLICT_DATA[iso3] || { hasActiveConflict: false, peaceIndex: null, conflictDeaths: null }

    // Get crime data
    const crimeInfo = CRIME_DATA[iso3] || { homicideRate: null, safetyIndex: null }

    return {
      iso3,
      iso2: info.iso2,
      name: info.name,
      region: info.region,
      subregion: info.subregion,
      population: POPULATION_DATA[iso3] || null,
      religion: religionData,
      democracy: democracyInfo,
      crime: crimeInfo,
      poverty: {
        povertyRate: povertyData[iso3] ?? null,
        gdpPerCapita: gdpData[iso3] ? Math.round(gdpData[iso3]) : null,
        hdi: hdiData[iso3] ?? HDI_DATA[iso3] ?? null,
      },
      gender: {
        wblIndex: genderData[iso3] ?? null,
        giiScore: GII_DATA[iso3] ?? null,
      },
      conflict: conflictInfo,
      sources: {
        religion: { source: 'CIA World Factbook', year: 2023 },
        democracy: { source: 'V-Dem / Freedom House', year: 2024 },
        crime: { source: 'UNODC / Global Peace Index', year: 2024 },
        poverty: { source: 'World Bank', year: 2023 },
        gender: { source: 'World Bank WBL', year: 2024 },
        conflict: { source: 'UCDP / Global Peace Index', year: 2024 },
      },
    }
  })

  // Write to file
  fs.writeFileSync(OUTPUT_PATH, JSON.stringify(countries, null, 2))
  console.log(`\nWrote ${countries.length} countries to ${OUTPUT_PATH}`)
}

// ============ STATIC DATA FROM SOURCES ============

const RELIGION_DATA: Record<string, { major: string; breakdown: Record<string, number> }> = {
  AFG: { major: 'Islam', breakdown: { Islam: 99.7, Other: 0.3 } },
  ALB: { major: 'Islam', breakdown: { Islam: 58.8, Christianity: 17, None: 24.2 } },
  DZA: { major: 'Islam', breakdown: { Islam: 99, Other: 1 } },
  ARG: { major: 'Christianity', breakdown: { Christianity: 79.6, None: 18.9, Other: 1.5 } },
  ARM: { major: 'Christianity', breakdown: { Christianity: 97, Other: 3 } },
  AUS: { major: 'Christianity', breakdown: { Christianity: 43.9, None: 38.9, Other: 17.2 } },
  AUT: { major: 'Christianity', breakdown: { Christianity: 66, Islam: 8, None: 22, Other: 4 } },
  AZE: { major: 'Islam', breakdown: { Islam: 97, Christianity: 3 } },
  BHR: { major: 'Islam', breakdown: { Islam: 73.7, Christianity: 9.3, Other: 17 } },
  BGD: { major: 'Islam', breakdown: { Islam: 89.1, Hinduism: 10, Other: 0.9 } },
  BLR: { major: 'Christianity', breakdown: { Christianity: 73, None: 25, Other: 2 } },
  BEL: { major: 'Christianity', breakdown: { Christianity: 57.1, Islam: 6.8, None: 35, Other: 1.1 } },
  BEN: { major: 'Christianity', breakdown: { Christianity: 52.2, Islam: 24.6, Folk: 17.9, Other: 5.3 } },
  BTN: { major: 'Buddhism', breakdown: { Buddhism: 74.8, Hinduism: 22.6, Other: 2.6 } },
  BOL: { major: 'Christianity', breakdown: { Christianity: 92.5, None: 4.1, Other: 3.4 } },
  BIH: { major: 'Islam', breakdown: { Islam: 50.7, Christianity: 46, Other: 3.3 } },
  BWA: { major: 'Christianity', breakdown: { Christianity: 79.1, None: 15.2, Other: 5.7 } },
  BRA: { major: 'Christianity', breakdown: { Christianity: 88.8, None: 8, Other: 3.2 } },
  BRN: { major: 'Islam', breakdown: { Islam: 80.9, Buddhism: 7.8, Christianity: 7.1, Other: 4.2 } },
  BGR: { major: 'Christianity', breakdown: { Christianity: 76, Islam: 10, None: 11.8, Other: 2.2 } },
  BFA: { major: 'Islam', breakdown: { Islam: 63.8, Christianity: 26.3, Folk: 9, Other: 0.9 } },
  BDI: { major: 'Christianity', breakdown: { Christianity: 93.5, Islam: 3.2, Other: 3.3 } },
  KHM: { major: 'Buddhism', breakdown: { Buddhism: 97.9, Islam: 1.1, Other: 1 } },
  CMR: { major: 'Christianity', breakdown: { Christianity: 70.7, Islam: 24.4, Folk: 3.2, Other: 1.7 } },
  CAN: { major: 'Christianity', breakdown: { Christianity: 53.3, None: 34.6, Islam: 4.9, Other: 7.2 } },
  CAF: { major: 'Christianity', breakdown: { Christianity: 89.5, Islam: 8.5, Other: 2 } },
  TCD: { major: 'Islam', breakdown: { Islam: 52.1, Christianity: 44.2, Folk: 2.3, Other: 1.4 } },
  CHL: { major: 'Christianity', breakdown: { Christianity: 70, None: 25.7, Other: 4.3 } },
  CHN: { major: 'None/Unaffiliated', breakdown: { None: 73.6, Buddhism: 15.9, Christianity: 5.2, Islam: 1.8, Other: 3.5 } },
  COL: { major: 'Christianity', breakdown: { Christianity: 92.1, None: 6, Other: 1.9 } },
  COD: { major: 'Christianity', breakdown: { Christianity: 95.8, Islam: 1.5, Other: 2.7 } },
  COG: { major: 'Christianity', breakdown: { Christianity: 88.5, None: 6.6, Islam: 1.6, Other: 3.3 } },
  CRI: { major: 'Christianity', breakdown: { Christianity: 84.3, None: 13.4, Other: 2.3 } },
  CIV: { major: 'Islam', breakdown: { Islam: 42.9, Christianity: 33.9, Folk: 12.6, None: 10.6 } },
  HRV: { major: 'Christianity', breakdown: { Christianity: 86.3, None: 9.4, Other: 4.3 } },
  CUB: { major: 'Christianity', breakdown: { Christianity: 59.2, None: 23, Folk: 17.4, Other: 0.4 } },
  CYP: { major: 'Christianity', breakdown: { Christianity: 72, Islam: 25.3, Other: 2.7 } },
  CZE: { major: 'None/Unaffiliated', breakdown: { None: 78.4, Christianity: 19.3, Other: 2.3 } },
  DNK: { major: 'Christianity', breakdown: { Christianity: 74.7, Islam: 5.5, None: 19.1, Other: 0.7 } },
  DJI: { major: 'Islam', breakdown: { Islam: 94.8, Christianity: 4.8, Other: 0.4 } },
  DOM: { major: 'Christianity', breakdown: { Christianity: 80.4, None: 11.6, Other: 8 } },
  ECU: { major: 'Christianity', breakdown: { Christianity: 92.5, None: 5.6, Other: 1.9 } },
  EGY: { major: 'Islam', breakdown: { Islam: 90, Christianity: 10 } },
  SLV: { major: 'Christianity', breakdown: { Christianity: 84.9, None: 13.1, Other: 2 } },
  GNQ: { major: 'Christianity', breakdown: { Christianity: 93, Folk: 5, Islam: 2 } },
  ERI: { major: 'Christianity', breakdown: { Christianity: 62.9, Islam: 36.6, Other: 0.5 } },
  EST: { major: 'None/Unaffiliated', breakdown: { None: 60.2, Christianity: 34, Other: 5.8 } },
  SWZ: { major: 'Christianity', breakdown: { Christianity: 90, Folk: 8, Other: 2 } },
  ETH: { major: 'Christianity', breakdown: { Christianity: 62.8, Islam: 33.9, Folk: 2.6, Other: 0.7 } },
  FIN: { major: 'Christianity', breakdown: { Christianity: 68.6, None: 29.4, Other: 2 } },
  FRA: { major: 'Christianity', breakdown: { Christianity: 51, Islam: 9, None: 37, Other: 3 } },
  GAB: { major: 'Christianity', breakdown: { Christianity: 82.3, Islam: 10.2, Folk: 5.7, Other: 1.8 } },
  GMB: { major: 'Islam', breakdown: { Islam: 95.7, Christianity: 4.2, Other: 0.1 } },
  GEO: { major: 'Christianity', breakdown: { Christianity: 88.1, Islam: 10.7, Other: 1.2 } },
  DEU: { major: 'Christianity', breakdown: { Christianity: 52.7, Islam: 6.7, None: 38.8, Other: 1.8 } },
  GHA: { major: 'Christianity', breakdown: { Christianity: 71.3, Islam: 19.9, Folk: 3.2, None: 5.6 } },
  GRC: { major: 'Christianity', breakdown: { Christianity: 90, Islam: 5.3, None: 3, Other: 1.7 } },
  GTM: { major: 'Christianity', breakdown: { Christianity: 88.6, None: 9.6, Other: 1.8 } },
  GIN: { major: 'Islam', breakdown: { Islam: 89.1, Christianity: 6.8, Folk: 2.9, Other: 1.2 } },
  GNB: { major: 'Islam', breakdown: { Islam: 46.1, Folk: 30.6, Christianity: 18.9, Other: 4.4 } },
  GUY: { major: 'Christianity', breakdown: { Christianity: 63.4, Hinduism: 24.8, Islam: 6.8, Other: 5 } },
  HTI: { major: 'Christianity', breakdown: { Christianity: 87, None: 10.6, Folk: 2.1, Other: 0.3 } },
  HND: { major: 'Christianity', breakdown: { Christianity: 87.6, None: 11.1, Other: 1.3 } },
  HUN: { major: 'Christianity', breakdown: { Christianity: 62.3, None: 27.2, Other: 10.5 } },
  ISL: { major: 'Christianity', breakdown: { Christianity: 79.2, None: 13.3, Other: 7.5 } },
  IND: { major: 'Hinduism', breakdown: { Hinduism: 79.8, Islam: 14.2, Christianity: 2.3, Other: 3.7 } },
  IDN: { major: 'Islam', breakdown: { Islam: 87.2, Christianity: 9.9, Hinduism: 1.7, Other: 1.2 } },
  IRN: { major: 'Islam', breakdown: { Islam: 99.4, Other: 0.6 } },
  IRQ: { major: 'Islam', breakdown: { Islam: 95.7, Christianity: 4, Other: 0.3 } },
  IRL: { major: 'Christianity', breakdown: { Christianity: 82.3, None: 14, Other: 3.7 } },
  ISR: { major: 'Judaism', breakdown: { Judaism: 74.2, Islam: 17.8, Christianity: 2, Other: 6 } },
  ITA: { major: 'Christianity', breakdown: { Christianity: 74.4, None: 22.6, Islam: 2.6, Other: 0.4 } },
  JAM: { major: 'Christianity', breakdown: { Christianity: 68.9, None: 21.3, Other: 9.8 } },
  JPN: { major: 'None/Unaffiliated', breakdown: { None: 62, Buddhism: 31.4, Shinto: 3.9, Christianity: 1.5, Other: 1.2 } },
  JOR: { major: 'Islam', breakdown: { Islam: 97.1, Christianity: 2.1, Other: 0.8 } },
  KAZ: { major: 'Islam', breakdown: { Islam: 70.2, Christianity: 26.3, None: 2.8, Other: 0.7 } },
  KEN: { major: 'Christianity', breakdown: { Christianity: 85.5, Islam: 10.9, Folk: 1.7, Other: 1.9 } },
  PRK: { major: 'None/Unaffiliated', breakdown: { None: 71.3, Folk: 12.3, Buddhism: 13.5, Christianity: 1.5, Other: 1.4 } },
  KOR: { major: 'None/Unaffiliated', breakdown: { None: 56.1, Christianity: 27.6, Buddhism: 15.5, Other: 0.8 } },
  KWT: { major: 'Islam', breakdown: { Islam: 76.7, Christianity: 17.3, Other: 6 } },
  KGZ: { major: 'Islam', breakdown: { Islam: 90, Christianity: 7, Other: 3 } },
  LAO: { major: 'Buddhism', breakdown: { Buddhism: 64.7, Folk: 31.5, Christianity: 1.7, Other: 2.1 } },
  LVA: { major: 'Christianity', breakdown: { Christianity: 55.2, None: 39.5, Other: 5.3 } },
  LBN: { major: 'Islam', breakdown: { Islam: 67.8, Christianity: 32.4, Other: 0.8 } },
  LSO: { major: 'Christianity', breakdown: { Christianity: 90.3, Folk: 6.2, None: 2.5, Other: 1 } },
  LBR: { major: 'Christianity', breakdown: { Christianity: 85.6, Islam: 12.2, Folk: 0.6, Other: 1.6 } },
  LBY: { major: 'Islam', breakdown: { Islam: 96.6, Christianity: 2.7, Other: 0.7 } },
  LTU: { major: 'Christianity', breakdown: { Christianity: 77.2, None: 19.9, Other: 2.9 } },
  LUX: { major: 'Christianity', breakdown: { Christianity: 63.8, None: 28.8, Islam: 3.2, Other: 4.2 } },
  MDG: { major: 'Christianity', breakdown: { Christianity: 85.3, Islam: 3, Folk: 4.5, None: 6.9, Other: 0.3 } },
  MWI: { major: 'Christianity', breakdown: { Christianity: 77.3, Islam: 13.8, Folk: 7.1, Other: 1.8 } },
  MYS: { major: 'Islam', breakdown: { Islam: 61.3, Buddhism: 19.8, Christianity: 9.2, Hinduism: 6.3, Other: 3.4 } },
  MLI: { major: 'Islam', breakdown: { Islam: 93.9, Christianity: 2.8, Folk: 2.6, Other: 0.7 } },
  MRT: { major: 'Islam', breakdown: { Islam: 99.9, Other: 0.1 } },
  MUS: { major: 'Hinduism', breakdown: { Hinduism: 48.5, Christianity: 32.7, Islam: 17.2, Other: 1.6 } },
  MEX: { major: 'Christianity', breakdown: { Christianity: 90.5, None: 8.1, Other: 1.4 } },
  MDA: { major: 'Christianity', breakdown: { Christianity: 96.8, None: 2.3, Other: 0.9 } },
  MNG: { major: 'Buddhism', breakdown: { Buddhism: 51.7, None: 40.6, Islam: 3.2, Shamanism: 2.5, Christianity: 2 } },
  MNE: { major: 'Christianity', breakdown: { Christianity: 72.1, Islam: 19.1, None: 6.2, Other: 2.6 } },
  MAR: { major: 'Islam', breakdown: { Islam: 99, Other: 1 } },
  MOZ: { major: 'Christianity', breakdown: { Christianity: 57.7, Islam: 17.9, None: 18.7, Folk: 5.3, Other: 0.4 } },
  MMR: { major: 'Buddhism', breakdown: { Buddhism: 87.9, Christianity: 6.2, Islam: 4.3, Other: 1.6 } },
  NAM: { major: 'Christianity', breakdown: { Christianity: 80, Folk: 10, None: 10 } },
  NPL: { major: 'Hinduism', breakdown: { Hinduism: 81.3, Buddhism: 9, Islam: 4.4, Christianity: 1.4, Other: 3.9 } },
  NLD: { major: 'None/Unaffiliated', breakdown: { None: 55.1, Christianity: 37.3, Islam: 5.1, Other: 2.5 } },
  NZL: { major: 'Christianity', breakdown: { Christianity: 36.5, None: 48.6, Hinduism: 2.6, Islam: 1.3, Other: 11 } },
  NIC: { major: 'Christianity', breakdown: { Christianity: 85.6, None: 12.5, Other: 1.9 } },
  NER: { major: 'Islam', breakdown: { Islam: 99.3, Christianity: 0.4, Other: 0.3 } },
  NGA: { major: 'Islam', breakdown: { Islam: 53.5, Christianity: 45.9, Other: 0.6 } },
  NOR: { major: 'Christianity', breakdown: { Christianity: 68.7, None: 21.1, Islam: 3.4, Other: 6.8 } },
  OMN: { major: 'Islam', breakdown: { Islam: 85.9, Christianity: 6.4, Hinduism: 5.5, Other: 2.2 } },
  PAK: { major: 'Islam', breakdown: { Islam: 96.5, Hinduism: 1.9, Christianity: 1.6, Other: 0 } },
  PAN: { major: 'Christianity', breakdown: { Christianity: 91.2, None: 4.7, Other: 4.1 } },
  PNG: { major: 'Christianity', breakdown: { Christianity: 95.6, Folk: 3.3, Other: 1.1 } },
  PRY: { major: 'Christianity', breakdown: { Christianity: 96.1, None: 2.6, Other: 1.3 } },
  PER: { major: 'Christianity', breakdown: { Christianity: 93.8, None: 4.6, Other: 1.6 } },
  PHL: { major: 'Christianity', breakdown: { Christianity: 92.6, Islam: 5.6, Other: 1.8 } },
  POL: { major: 'Christianity', breakdown: { Christianity: 87.2, None: 11.5, Other: 1.3 } },
  PRT: { major: 'Christianity', breakdown: { Christianity: 84.3, None: 14.3, Other: 1.4 } },
  QAT: { major: 'Islam', breakdown: { Islam: 67.7, Christianity: 13.8, Hinduism: 13.8, Other: 4.7 } },
  ROU: { major: 'Christianity', breakdown: { Christianity: 92.3, None: 6.3, Islam: 0.9, Other: 0.5 } },
  RUS: { major: 'Christianity', breakdown: { Christianity: 73.3, Islam: 10, None: 13, Other: 3.7 } },
  RWA: { major: 'Christianity', breakdown: { Christianity: 93.4, Islam: 2.2, None: 3.4, Other: 1 } },
  SAU: { major: 'Islam', breakdown: { Islam: 93, Christianity: 4.4, Other: 2.6 } },
  SEN: { major: 'Islam', breakdown: { Islam: 96.1, Christianity: 3.8, Other: 0.1 } },
  SRB: { major: 'Christianity', breakdown: { Christianity: 87.6, Islam: 3.1, None: 6.6, Other: 2.7 } },
  SLE: { major: 'Islam', breakdown: { Islam: 78.6, Christianity: 20.8, Other: 0.6 } },
  SGP: { major: 'Buddhism', breakdown: { Buddhism: 31.1, Christianity: 18.9, None: 20, Islam: 15.6, Hinduism: 5, Other: 9.4 } },
  SVK: { major: 'Christianity', breakdown: { Christianity: 74.8, None: 23.8, Other: 1.4 } },
  SVN: { major: 'Christianity', breakdown: { Christianity: 71.6, None: 22.8, Islam: 3.2, Other: 2.4 } },
  SOM: { major: 'Islam', breakdown: { Islam: 99.9, Other: 0.1 } },
  ZAF: { major: 'Christianity', breakdown: { Christianity: 79.7, None: 15.1, Islam: 1.7, Hinduism: 1.1, Other: 2.4 } },
  SSD: { major: 'Christianity', breakdown: { Christianity: 60.5, Folk: 32.9, Islam: 6.2, Other: 0.4 } },
  ESP: { major: 'Christianity', breakdown: { Christianity: 58.2, None: 38.9, Islam: 2.4, Other: 0.5 } },
  LKA: { major: 'Buddhism', breakdown: { Buddhism: 70.2, Hinduism: 12.6, Islam: 9.7, Christianity: 7.4, Other: 0.1 } },
  SDN: { major: 'Islam', breakdown: { Islam: 91, Christianity: 5.4, Folk: 2.8, Other: 0.8 } },
  SUR: { major: 'Christianity', breakdown: { Christianity: 48.4, Hinduism: 22.3, Islam: 13.9, None: 7.5, Other: 7.9 } },
  SWE: { major: 'Christianity', breakdown: { Christianity: 60.2, None: 32.4, Islam: 5.1, Other: 2.3 } },
  CHE: { major: 'Christianity', breakdown: { Christianity: 62.6, None: 29.4, Islam: 5.3, Other: 2.7 } },
  SYR: { major: 'Islam', breakdown: { Islam: 87, Christianity: 10, Other: 3 } },
  TWN: { major: 'Buddhism', breakdown: { Buddhism: 35.1, Folk: 33, Christianity: 3.9, None: 26.7, Other: 1.3 } },
  TJK: { major: 'Islam', breakdown: { Islam: 96.4, Christianity: 1.1, Other: 2.5 } },
  TZA: { major: 'Christianity', breakdown: { Christianity: 63.1, Islam: 34.1, Folk: 1.8, Other: 1 } },
  THA: { major: 'Buddhism', breakdown: { Buddhism: 94.6, Islam: 4.3, Christianity: 1, Other: 0.1 } },
  TLS: { major: 'Christianity', breakdown: { Christianity: 99.1, Islam: 0.2, Other: 0.7 } },
  TGO: { major: 'Christianity', breakdown: { Christianity: 43.7, Folk: 35.6, Islam: 14, None: 6.2, Other: 0.5 } },
  TTO: { major: 'Christianity', breakdown: { Christianity: 63.2, Hinduism: 18.2, Islam: 5, None: 11.1, Other: 2.5 } },
  TUN: { major: 'Islam', breakdown: { Islam: 99.1, Christianity: 0.5, Other: 0.4 } },
  TUR: { major: 'Islam', breakdown: { Islam: 98.6, Christianity: 0.3, Other: 1.1 } },
  TKM: { major: 'Islam', breakdown: { Islam: 93, Christianity: 6.4, Other: 0.6 } },
  UGA: { major: 'Christianity', breakdown: { Christianity: 84.4, Islam: 13.7, Folk: 1, Other: 0.9 } },
  UKR: { major: 'Christianity', breakdown: { Christianity: 87.3, None: 7.7, Islam: 1.1, Other: 3.9 } },
  ARE: { major: 'Islam', breakdown: { Islam: 76, Christianity: 9, Other: 15 } },
  GBR: { major: 'Christianity', breakdown: { Christianity: 46.3, None: 37.2, Islam: 6.7, Other: 9.8 } },
  USA: { major: 'Christianity', breakdown: { Christianity: 70.6, None: 22.8, Judaism: 1.9, Islam: 1.1, Other: 3.6 } },
  URY: { major: 'Christianity', breakdown: { Christianity: 57.6, None: 40.5, Other: 1.9 } },
  UZB: { major: 'Islam', breakdown: { Islam: 93.3, Christianity: 3.8, Other: 2.9 } },
  VEN: { major: 'Christianity', breakdown: { Christianity: 89, None: 9, Other: 2 } },
  VNM: { major: 'None/Unaffiliated', breakdown: { None: 29.6, Buddhism: 16.4, Christianity: 8.2, Folk: 45.3, Other: 0.5 } },
  YEM: { major: 'Islam', breakdown: { Islam: 99.1, Other: 0.9 } },
  ZMB: { major: 'Christianity', breakdown: { Christianity: 95.5, Islam: 0.5, Folk: 2.7, Other: 1.3 } },
  ZWE: { major: 'Christianity', breakdown: { Christianity: 86.8, Folk: 4.5, None: 7.9, Other: 0.8 } },
}

// Democracy scores (0-100 scale, combined from V-Dem and Freedom House)
const DEMOCRACY_DATA: Record<string, { score: number; freedomScore: number | null; vdemScore: number | null }> = {
  AFG: { score: 10, freedomScore: 10, vdemScore: 0.10 },
  ALB: { score: 53, freedomScore: 67, vdemScore: 0.46 },
  DZA: { score: 23, freedomScore: 32, vdemScore: 0.19 },
  ARG: { score: 70, freedomScore: 84, vdemScore: 0.65 },
  ARM: { score: 45, freedomScore: 54, vdemScore: 0.39 },
  AUS: { score: 90, freedomScore: 95, vdemScore: 0.88 },
  AUT: { score: 89, freedomScore: 93, vdemScore: 0.87 },
  AZE: { score: 9, freedomScore: 9, vdemScore: 0.08 },
  BHR: { score: 11, freedomScore: 12, vdemScore: 0.09 },
  BGD: { score: 32, freedomScore: 39, vdemScore: 0.28 },
  BLR: { score: 8, freedomScore: 8, vdemScore: 0.07 },
  BEL: { score: 89, freedomScore: 96, vdemScore: 0.86 },
  BEN: { score: 45, freedomScore: 64, vdemScore: 0.35 },
  BTN: { score: 50, freedomScore: 61, vdemScore: 0.44 },
  BOL: { score: 52, freedomScore: 66, vdemScore: 0.45 },
  BIH: { score: 48, freedomScore: 53, vdemScore: 0.45 },
  BWA: { score: 68, freedomScore: 72, vdemScore: 0.66 },
  BRA: { score: 66, freedomScore: 73, vdemScore: 0.63 },
  BRN: { score: 7, freedomScore: 28, vdemScore: 0.04 },
  BGR: { score: 67, freedomScore: 79, vdemScore: 0.60 },
  BFA: { score: 28, freedomScore: 52, vdemScore: 0.17 },
  BDI: { score: 14, freedomScore: 14, vdemScore: 0.12 },
  KHM: { score: 15, freedomScore: 24, vdemScore: 0.11 },
  CMR: { score: 16, freedomScore: 16, vdemScore: 0.13 },
  CAN: { score: 92, freedomScore: 98, vdemScore: 0.89 },
  CAF: { score: 9, freedomScore: 9, vdemScore: 0.08 },
  TCD: { score: 12, freedomScore: 17, vdemScore: 0.10 },
  CHL: { score: 80, freedomScore: 93, vdemScore: 0.73 },
  CHN: { score: 8, freedomScore: 9, vdemScore: 0.06 },
  COL: { score: 60, freedomScore: 63, vdemScore: 0.58 },
  COD: { score: 18, freedomScore: 20, vdemScore: 0.15 },
  COG: { score: 17, freedomScore: 20, vdemScore: 0.14 },
  CRI: { score: 86, freedomScore: 91, vdemScore: 0.83 },
  CIV: { score: 35, freedomScore: 45, vdemScore: 0.29 },
  HRV: { score: 72, freedomScore: 85, vdemScore: 0.66 },
  CUB: { score: 10, freedomScore: 13, vdemScore: 0.08 },
  CYP: { score: 78, freedomScore: 94, vdemScore: 0.69 },
  CZE: { score: 78, freedomScore: 91, vdemScore: 0.71 },
  DNK: { score: 94, freedomScore: 97, vdemScore: 0.92 },
  DJI: { score: 15, freedomScore: 24, vdemScore: 0.11 },
  DOM: { score: 58, freedomScore: 69, vdemScore: 0.52 },
  ECU: { score: 55, freedomScore: 67, vdemScore: 0.48 },
  EGY: { score: 18, freedomScore: 18, vdemScore: 0.15 },
  SLV: { score: 48, freedomScore: 56, vdemScore: 0.43 },
  GNQ: { score: 6, freedomScore: 5, vdemScore: 0.05 },
  ERI: { score: 3, freedomScore: 3, vdemScore: 0.02 },
  EST: { score: 87, freedomScore: 94, vdemScore: 0.83 },
  SWZ: { score: 8, freedomScore: 19, vdemScore: 0.06 },
  ETH: { score: 20, freedomScore: 22, vdemScore: 0.17 },
  FIN: { score: 95, freedomScore: 100, vdemScore: 0.92 },
  FRA: { score: 78, freedomScore: 89, vdemScore: 0.72 },
  GAB: { score: 22, freedomScore: 23, vdemScore: 0.19 },
  GMB: { score: 38, freedomScore: 45, vdemScore: 0.34 },
  GEO: { score: 52, freedomScore: 58, vdemScore: 0.48 },
  DEU: { score: 90, freedomScore: 94, vdemScore: 0.88 },
  GHA: { score: 65, freedomScore: 80, vdemScore: 0.57 },
  GRC: { score: 72, freedomScore: 87, vdemScore: 0.64 },
  GTM: { score: 45, freedomScore: 51, vdemScore: 0.41 },
  GIN: { score: 22, freedomScore: 28, vdemScore: 0.19 },
  GNB: { score: 32, freedomScore: 43, vdemScore: 0.27 },
  GUY: { score: 60, freedomScore: 73, vdemScore: 0.53 },
  HTI: { score: 22, freedomScore: 32, vdemScore: 0.18 },
  HND: { score: 42, freedomScore: 48, vdemScore: 0.38 },
  HUN: { score: 48, freedomScore: 69, vdemScore: 0.36 },
  ISL: { score: 93, freedomScore: 95, vdemScore: 0.92 },
  IND: { score: 50, freedomScore: 66, vdemScore: 0.41 },
  IDN: { score: 55, freedomScore: 58, vdemScore: 0.54 },
  IRN: { score: 14, freedomScore: 14, vdemScore: 0.12 },
  IRQ: { score: 29, freedomScore: 29, vdemScore: 0.26 },
  IRL: { score: 91, freedomScore: 97, vdemScore: 0.88 },
  ISR: { score: 68, freedomScore: 77, vdemScore: 0.63 },
  ITA: { score: 78, freedomScore: 90, vdemScore: 0.71 },
  JAM: { score: 72, freedomScore: 80, vdemScore: 0.68 },
  JPN: { score: 83, freedomScore: 96, vdemScore: 0.76 },
  JOR: { score: 30, freedomScore: 33, vdemScore: 0.27 },
  KAZ: { score: 15, freedomScore: 23, vdemScore: 0.11 },
  KEN: { score: 45, freedomScore: 48, vdemScore: 0.43 },
  PRK: { score: 3, freedomScore: 3, vdemScore: 0.02 },
  KOR: { score: 80, freedomScore: 83, vdemScore: 0.79 },
  KWT: { score: 32, freedomScore: 36, vdemScore: 0.29 },
  KGZ: { score: 28, freedomScore: 28, vdemScore: 0.25 },
  LAO: { score: 9, freedomScore: 13, vdemScore: 0.07 },
  LVA: { score: 82, freedomScore: 89, vdemScore: 0.78 },
  LBN: { score: 38, freedomScore: 44, vdemScore: 0.35 },
  LSO: { score: 52, freedomScore: 63, vdemScore: 0.46 },
  LBR: { score: 50, freedomScore: 60, vdemScore: 0.45 },
  LBY: { score: 9, freedomScore: 9, vdemScore: 0.08 },
  LTU: { score: 83, freedomScore: 89, vdemScore: 0.80 },
  LUX: { score: 92, freedomScore: 97, vdemScore: 0.89 },
  MDG: { score: 48, freedomScore: 61, vdemScore: 0.41 },
  MWI: { score: 52, freedomScore: 65, vdemScore: 0.45 },
  MYS: { score: 48, freedomScore: 51, vdemScore: 0.46 },
  MLI: { score: 23, freedomScore: 31, vdemScore: 0.19 },
  MRT: { score: 25, freedomScore: 35, vdemScore: 0.21 },
  MUS: { score: 75, freedomScore: 89, vdemScore: 0.67 },
  MEX: { score: 55, freedomScore: 60, vdemScore: 0.52 },
  MDA: { score: 52, freedomScore: 61, vdemScore: 0.47 },
  MNG: { score: 62, freedomScore: 84, vdemScore: 0.50 },
  MNE: { score: 55, freedomScore: 67, vdemScore: 0.48 },
  MAR: { score: 35, freedomScore: 37, vdemScore: 0.33 },
  MOZ: { score: 35, freedomScore: 43, vdemScore: 0.31 },
  MMR: { score: 12, freedomScore: 9, vdemScore: 0.13 },
  NAM: { score: 68, freedomScore: 77, vdemScore: 0.63 },
  NPL: { score: 50, freedomScore: 56, vdemScore: 0.47 },
  NLD: { score: 92, freedomScore: 97, vdemScore: 0.89 },
  NZL: { score: 95, freedomScore: 99, vdemScore: 0.93 },
  NIC: { score: 18, freedomScore: 19, vdemScore: 0.16 },
  NER: { score: 27, freedomScore: 48, vdemScore: 0.17 },
  NGA: { score: 40, freedomScore: 43, vdemScore: 0.38 },
  NOR: { score: 96, freedomScore: 100, vdemScore: 0.94 },
  OMN: { score: 20, freedomScore: 23, vdemScore: 0.17 },
  PAK: { score: 35, freedomScore: 37, vdemScore: 0.33 },
  PAN: { score: 68, freedomScore: 83, vdemScore: 0.60 },
  PNG: { score: 55, freedomScore: 62, vdemScore: 0.51 },
  PRY: { score: 52, freedomScore: 65, vdemScore: 0.45 },
  PER: { score: 55, freedomScore: 70, vdemScore: 0.47 },
  PHL: { score: 52, freedomScore: 55, vdemScore: 0.50 },
  POL: { score: 62, freedomScore: 81, vdemScore: 0.52 },
  PRT: { score: 87, freedomScore: 96, vdemScore: 0.82 },
  QAT: { score: 18, freedomScore: 25, vdemScore: 0.14 },
  ROU: { score: 68, freedomScore: 81, vdemScore: 0.61 },
  RUS: { score: 16, freedomScore: 16, vdemScore: 0.14 },
  RWA: { score: 18, freedomScore: 21, vdemScore: 0.15 },
  SAU: { score: 7, freedomScore: 8, vdemScore: 0.05 },
  SEN: { score: 52, freedomScore: 71, vdemScore: 0.43 },
  SRB: { score: 55, freedomScore: 62, vdemScore: 0.51 },
  SLE: { score: 48, freedomScore: 54, vdemScore: 0.44 },
  SGP: { score: 45, freedomScore: 47, vdemScore: 0.44 },
  SVK: { score: 72, freedomScore: 88, vdemScore: 0.63 },
  SVN: { score: 80, freedomScore: 90, vdemScore: 0.75 },
  SOM: { score: 7, freedomScore: 7, vdemScore: 0.06 },
  ZAF: { score: 68, freedomScore: 79, vdemScore: 0.62 },
  SSD: { score: 4, freedomScore: 4, vdemScore: 0.03 },
  ESP: { score: 81, freedomScore: 90, vdemScore: 0.76 },
  LKA: { score: 48, freedomScore: 56, vdemScore: 0.43 },
  SDN: { score: 9, freedomScore: 9, vdemScore: 0.08 },
  SUR: { score: 58, freedomScore: 77, vdemScore: 0.47 },
  SWE: { score: 95, freedomScore: 100, vdemScore: 0.92 },
  CHE: { score: 92, freedomScore: 96, vdemScore: 0.90 },
  SYR: { score: 5, freedomScore: 1, vdemScore: 0.06 },
  TWN: { score: 87, freedomScore: 94, vdemScore: 0.83 },
  TJK: { score: 10, freedomScore: 8, vdemScore: 0.09 },
  TZA: { score: 38, freedomScore: 34, vdemScore: 0.40 },
  THA: { score: 28, freedomScore: 29, vdemScore: 0.27 },
  TLS: { score: 58, freedomScore: 71, vdemScore: 0.51 },
  TGO: { score: 28, freedomScore: 43, vdemScore: 0.22 },
  TTO: { score: 70, freedomScore: 81, vdemScore: 0.64 },
  TUN: { score: 35, freedomScore: 31, vdemScore: 0.38 },
  TUR: { score: 28, freedomScore: 32, vdemScore: 0.26 },
  TKM: { score: 3, freedomScore: 2, vdemScore: 0.03 },
  UGA: { score: 32, freedomScore: 34, vdemScore: 0.30 },
  UKR: { score: 50, freedomScore: 50, vdemScore: 0.50 },
  ARE: { score: 17, freedomScore: 18, vdemScore: 0.15 },
  GBR: { score: 85, freedomScore: 91, vdemScore: 0.82 },
  USA: { score: 78, freedomScore: 83, vdemScore: 0.76 },
  URY: { score: 88, freedomScore: 97, vdemScore: 0.84 },
  UZB: { score: 12, freedomScore: 11, vdemScore: 0.10 },
  VEN: { score: 15, freedomScore: 14, vdemScore: 0.14 },
  VNM: { score: 12, freedomScore: 19, vdemScore: 0.09 },
  YEM: { score: 9, freedomScore: 11, vdemScore: 0.07 },
  ZMB: { score: 48, freedomScore: 52, vdemScore: 0.45 },
  ZWE: { score: 22, freedomScore: 28, vdemScore: 0.19 },
}

// Conflict data
const CONFLICT_DATA: Record<string, { hasActiveConflict: boolean; peaceIndex: number | null; conflictDeaths: number | null }> = {
  AFG: { hasActiveConflict: true, peaceIndex: 3.45, conflictDeaths: 4500 },
  ALB: { hasActiveConflict: false, peaceIndex: 1.79, conflictDeaths: 0 },
  DZA: { hasActiveConflict: false, peaceIndex: 2.12, conflictDeaths: 50 },
  ARG: { hasActiveConflict: false, peaceIndex: 1.89, conflictDeaths: 0 },
  AUS: { hasActiveConflict: false, peaceIndex: 1.30, conflictDeaths: 0 },
  AUT: { hasActiveConflict: false, peaceIndex: 1.30, conflictDeaths: 0 },
  AZE: { hasActiveConflict: true, peaceIndex: 2.52, conflictDeaths: 200 },
  BGD: { hasActiveConflict: false, peaceIndex: 2.09, conflictDeaths: 50 },
  BEL: { hasActiveConflict: false, peaceIndex: 1.52, conflictDeaths: 0 },
  BOL: { hasActiveConflict: false, peaceIndex: 2.04, conflictDeaths: 0 },
  BRA: { hasActiveConflict: false, peaceIndex: 2.38, conflictDeaths: 200 },
  BGR: { hasActiveConflict: false, peaceIndex: 1.60, conflictDeaths: 0 },
  BFA: { hasActiveConflict: true, peaceIndex: 2.72, conflictDeaths: 2500 },
  MMR: { hasActiveConflict: true, peaceIndex: 2.80, conflictDeaths: 3500 },
  BDI: { hasActiveConflict: false, peaceIndex: 2.41, conflictDeaths: 100 },
  CMR: { hasActiveConflict: true, peaceIndex: 2.56, conflictDeaths: 800 },
  CAN: { hasActiveConflict: false, peaceIndex: 1.31, conflictDeaths: 0 },
  CAF: { hasActiveConflict: true, peaceIndex: 3.02, conflictDeaths: 600 },
  TCD: { hasActiveConflict: true, peaceIndex: 2.64, conflictDeaths: 400 },
  CHL: { hasActiveConflict: false, peaceIndex: 1.75, conflictDeaths: 0 },
  CHN: { hasActiveConflict: false, peaceIndex: 1.95, conflictDeaths: 0 },
  COL: { hasActiveConflict: true, peaceIndex: 2.73, conflictDeaths: 700 },
  COD: { hasActiveConflict: true, peaceIndex: 3.11, conflictDeaths: 2000 },
  CUB: { hasActiveConflict: false, peaceIndex: 1.95, conflictDeaths: 0 },
  CZE: { hasActiveConflict: false, peaceIndex: 1.34, conflictDeaths: 0 },
  DNK: { hasActiveConflict: false, peaceIndex: 1.30, conflictDeaths: 0 },
  ECU: { hasActiveConflict: false, peaceIndex: 2.04, conflictDeaths: 50 },
  EGY: { hasActiveConflict: true, peaceIndex: 2.38, conflictDeaths: 300 },
  SLV: { hasActiveConflict: false, peaceIndex: 2.25, conflictDeaths: 50 },
  ERI: { hasActiveConflict: false, peaceIndex: 2.40, conflictDeaths: 0 },
  EST: { hasActiveConflict: false, peaceIndex: 1.43, conflictDeaths: 0 },
  ETH: { hasActiveConflict: true, peaceIndex: 2.82, conflictDeaths: 5000 },
  FIN: { hasActiveConflict: false, peaceIndex: 1.29, conflictDeaths: 0 },
  FRA: { hasActiveConflict: false, peaceIndex: 1.89, conflictDeaths: 0 },
  DEU: { hasActiveConflict: false, peaceIndex: 1.46, conflictDeaths: 0 },
  GHA: { hasActiveConflict: false, peaceIndex: 1.78, conflictDeaths: 0 },
  GRC: { hasActiveConflict: false, peaceIndex: 1.94, conflictDeaths: 0 },
  GTM: { hasActiveConflict: false, peaceIndex: 2.41, conflictDeaths: 100 },
  HTI: { hasActiveConflict: true, peaceIndex: 2.98, conflictDeaths: 800 },
  HND: { hasActiveConflict: false, peaceIndex: 2.34, conflictDeaths: 50 },
  HUN: { hasActiveConflict: false, peaceIndex: 1.61, conflictDeaths: 0 },
  ISL: { hasActiveConflict: false, peaceIndex: 1.12, conflictDeaths: 0 },
  IND: { hasActiveConflict: true, peaceIndex: 2.51, conflictDeaths: 1500 },
  IDN: { hasActiveConflict: false, peaceIndex: 1.93, conflictDeaths: 50 },
  IRN: { hasActiveConflict: false, peaceIndex: 2.38, conflictDeaths: 100 },
  IRQ: { hasActiveConflict: true, peaceIndex: 2.90, conflictDeaths: 1000 },
  IRL: { hasActiveConflict: false, peaceIndex: 1.31, conflictDeaths: 0 },
  ISR: { hasActiveConflict: true, peaceIndex: 2.75, conflictDeaths: 1500 },
  ITA: { hasActiveConflict: false, peaceIndex: 1.69, conflictDeaths: 0 },
  JPN: { hasActiveConflict: false, peaceIndex: 1.34, conflictDeaths: 0 },
  JOR: { hasActiveConflict: false, peaceIndex: 1.93, conflictDeaths: 0 },
  KAZ: { hasActiveConflict: false, peaceIndex: 1.89, conflictDeaths: 0 },
  KEN: { hasActiveConflict: false, peaceIndex: 2.35, conflictDeaths: 100 },
  PRK: { hasActiveConflict: false, peaceIndex: 2.84, conflictDeaths: 0 },
  KOR: { hasActiveConflict: false, peaceIndex: 1.77, conflictDeaths: 0 },
  KWT: { hasActiveConflict: false, peaceIndex: 1.83, conflictDeaths: 0 },
  LBN: { hasActiveConflict: true, peaceIndex: 2.72, conflictDeaths: 500 },
  LBY: { hasActiveConflict: true, peaceIndex: 2.87, conflictDeaths: 700 },
  MDG: { hasActiveConflict: false, peaceIndex: 1.95, conflictDeaths: 0 },
  MYS: { hasActiveConflict: false, peaceIndex: 1.63, conflictDeaths: 0 },
  MLI: { hasActiveConflict: true, peaceIndex: 2.91, conflictDeaths: 1500 },
  MEX: { hasActiveConflict: true, peaceIndex: 2.56, conflictDeaths: 2000 },
  MAR: { hasActiveConflict: false, peaceIndex: 1.90, conflictDeaths: 0 },
  MOZ: { hasActiveConflict: true, peaceIndex: 2.40, conflictDeaths: 600 },
  NAM: { hasActiveConflict: false, peaceIndex: 1.70, conflictDeaths: 0 },
  NPL: { hasActiveConflict: false, peaceIndex: 1.98, conflictDeaths: 0 },
  NLD: { hasActiveConflict: false, peaceIndex: 1.43, conflictDeaths: 0 },
  NZL: { hasActiveConflict: false, peaceIndex: 1.22, conflictDeaths: 0 },
  NER: { hasActiveConflict: true, peaceIndex: 2.61, conflictDeaths: 500 },
  NGA: { hasActiveConflict: true, peaceIndex: 2.81, conflictDeaths: 3000 },
  NOR: { hasActiveConflict: false, peaceIndex: 1.32, conflictDeaths: 0 },
  PAK: { hasActiveConflict: true, peaceIndex: 2.78, conflictDeaths: 1500 },
  PAN: { hasActiveConflict: false, peaceIndex: 1.92, conflictDeaths: 0 },
  PER: { hasActiveConflict: false, peaceIndex: 2.10, conflictDeaths: 50 },
  PHL: { hasActiveConflict: true, peaceIndex: 2.46, conflictDeaths: 400 },
  POL: { hasActiveConflict: false, peaceIndex: 1.55, conflictDeaths: 0 },
  PRT: { hasActiveConflict: false, peaceIndex: 1.30, conflictDeaths: 0 },
  ROU: { hasActiveConflict: false, peaceIndex: 1.70, conflictDeaths: 0 },
  RUS: { hasActiveConflict: true, peaceIndex: 3.15, conflictDeaths: 15000 },
  SAU: { hasActiveConflict: false, peaceIndex: 2.41, conflictDeaths: 0 },
  SEN: { hasActiveConflict: false, peaceIndex: 2.05, conflictDeaths: 50 },
  SRB: { hasActiveConflict: false, peaceIndex: 1.95, conflictDeaths: 0 },
  SGP: { hasActiveConflict: false, peaceIndex: 1.33, conflictDeaths: 0 },
  SVK: { hasActiveConflict: false, peaceIndex: 1.50, conflictDeaths: 0 },
  SVN: { hasActiveConflict: false, peaceIndex: 1.33, conflictDeaths: 0 },
  SOM: { hasActiveConflict: true, peaceIndex: 3.36, conflictDeaths: 2500 },
  ZAF: { hasActiveConflict: false, peaceIndex: 2.35, conflictDeaths: 0 },
  SSD: { hasActiveConflict: true, peaceIndex: 3.18, conflictDeaths: 1500 },
  ESP: { hasActiveConflict: false, peaceIndex: 1.55, conflictDeaths: 0 },
  LKA: { hasActiveConflict: false, peaceIndex: 2.02, conflictDeaths: 0 },
  SDN: { hasActiveConflict: true, peaceIndex: 3.23, conflictDeaths: 8000 },
  SWE: { hasActiveConflict: false, peaceIndex: 1.45, conflictDeaths: 0 },
  CHE: { hasActiveConflict: false, peaceIndex: 1.36, conflictDeaths: 0 },
  SYR: { hasActiveConflict: true, peaceIndex: 3.32, conflictDeaths: 3000 },
  TWN: { hasActiveConflict: false, peaceIndex: 1.62, conflictDeaths: 0 },
  TZA: { hasActiveConflict: false, peaceIndex: 1.90, conflictDeaths: 0 },
  THA: { hasActiveConflict: true, peaceIndex: 2.20, conflictDeaths: 200 },
  TUR: { hasActiveConflict: true, peaceIndex: 2.63, conflictDeaths: 500 },
  UGA: { hasActiveConflict: false, peaceIndex: 2.20, conflictDeaths: 100 },
  UKR: { hasActiveConflict: true, peaceIndex: 3.04, conflictDeaths: 20000 },
  ARE: { hasActiveConflict: false, peaceIndex: 1.83, conflictDeaths: 0 },
  GBR: { hasActiveConflict: false, peaceIndex: 1.69, conflictDeaths: 0 },
  USA: { hasActiveConflict: false, peaceIndex: 2.11, conflictDeaths: 0 },
  URY: { hasActiveConflict: false, peaceIndex: 1.62, conflictDeaths: 0 },
  UZB: { hasActiveConflict: false, peaceIndex: 2.10, conflictDeaths: 0 },
  VEN: { hasActiveConflict: false, peaceIndex: 2.51, conflictDeaths: 100 },
  VNM: { hasActiveConflict: false, peaceIndex: 1.83, conflictDeaths: 0 },
  YEM: { hasActiveConflict: true, peaceIndex: 3.38, conflictDeaths: 4000 },
  ZMB: { hasActiveConflict: false, peaceIndex: 1.88, conflictDeaths: 0 },
  ZWE: { hasActiveConflict: false, peaceIndex: 2.22, conflictDeaths: 0 },
}

// Crime data
const CRIME_DATA: Record<string, { homicideRate: number | null; safetyIndex: number | null }> = {
  AFG: { homicideRate: 6.5, safetyIndex: 15 },
  ARG: { homicideRate: 4.6, safetyIndex: 41 },
  AUS: { homicideRate: 0.9, safetyIndex: 58 },
  AUT: { homicideRate: 0.7, safetyIndex: 74 },
  BRA: { homicideRate: 22.4, safetyIndex: 32 },
  CAN: { homicideRate: 2.0, safetyIndex: 58 },
  CHN: { homicideRate: 0.5, safetyIndex: 65 },
  COL: { homicideRate: 25.3, safetyIndex: 42 },
  DEU: { homicideRate: 0.8, safetyIndex: 65 },
  EGY: { homicideRate: 2.5, safetyIndex: 47 },
  FRA: { homicideRate: 1.2, safetyIndex: 47 },
  GBR: { homicideRate: 1.2, safetyIndex: 52 },
  IND: { homicideRate: 2.9, safetyIndex: 49 },
  IDN: { homicideRate: 0.4, safetyIndex: 54 },
  IRN: { homicideRate: 2.5, safetyIndex: 51 },
  ITA: { homicideRate: 0.5, safetyIndex: 54 },
  JPN: { homicideRate: 0.2, safetyIndex: 77 },
  KOR: { homicideRate: 0.6, safetyIndex: 72 },
  MEX: { homicideRate: 28.4, safetyIndex: 38 },
  NGA: { homicideRate: 6.3, safetyIndex: 35 },
  PAK: { homicideRate: 3.9, safetyIndex: 38 },
  PHL: { homicideRate: 4.4, safetyIndex: 48 },
  POL: { homicideRate: 0.7, safetyIndex: 68 },
  RUS: { homicideRate: 7.3, safetyIndex: 53 },
  SAU: { homicideRate: 1.5, safetyIndex: 68 },
  SGP: { homicideRate: 0.2, safetyIndex: 84 },
  ESP: { homicideRate: 0.6, safetyIndex: 62 },
  TUR: { homicideRate: 2.5, safetyIndex: 55 },
  USA: { homicideRate: 6.3, safetyIndex: 51 },
  VEN: { homicideRate: 40.4, safetyIndex: 19 },
  VNM: { homicideRate: 1.5, safetyIndex: 58 },
  ZAF: { homicideRate: 33.5, safetyIndex: 23 },
}

// Population data (in millions)
const POPULATION_DATA: Record<string, number> = {
  AFG: 40100000, ALB: 2800000, DZA: 44700000, ARG: 45800000, ARM: 2800000,
  AUS: 26000000, AUT: 9000000, AZE: 10100000, BHR: 1500000, BGD: 171000000,
  BLR: 9200000, BEL: 11600000, BEN: 13300000, BTN: 780000, BOL: 12100000,
  BIH: 3200000, BWA: 2600000, BRA: 215000000, BRN: 450000, BGR: 6900000,
  BFA: 22100000, BDI: 12900000, KHM: 17000000, CMR: 28100000, CAN: 39000000,
  CAF: 5500000, TCD: 17700000, CHL: 19500000, CHN: 1412000000, COL: 52000000,
  COD: 99000000, COG: 6000000, CRI: 5200000, CIV: 28200000, HRV: 3900000,
  CUB: 11200000, CYP: 1300000, CZE: 10500000, DNK: 5900000, DJI: 1100000,
  DOM: 11200000, ECU: 18000000, EGY: 109000000, SLV: 6300000, GNQ: 1700000,
  ERI: 3700000, EST: 1400000, SWZ: 1200000, ETH: 123000000, FIN: 5500000,
  FRA: 68000000, GAB: 2400000, GMB: 2700000, GEO: 3700000, DEU: 84000000,
  GHA: 33500000, GRC: 10400000, GTM: 18000000, GIN: 14000000, GNB: 2100000,
  GUY: 800000, HTI: 11600000, HND: 10400000, HUN: 9700000, ISL: 380000,
  IND: 1428000000, IDN: 277000000, IRN: 87500000, IRQ: 44500000, IRL: 5200000,
  ISR: 9300000, ITA: 59000000, JAM: 2800000, JPN: 124000000, JOR: 11300000,
  KAZ: 19600000, KEN: 54000000, PRK: 26100000, KOR: 51700000, KWT: 4300000,
  KGZ: 6700000, LAO: 7500000, LVA: 1800000, LBN: 5300000, LSO: 2200000,
  LBR: 5300000, LBY: 7000000, LTU: 2800000, LUX: 660000, MDG: 30300000,
  MWI: 20400000, MYS: 34300000, MLI: 22400000, MRT: 4800000, MUS: 1300000,
  MEX: 128000000, MDA: 2500000, MNG: 3400000, MNE: 620000, MAR: 37800000,
  MOZ: 33000000, MMR: 54800000, NAM: 2600000, NPL: 30500000, NLD: 17700000,
  NZL: 5100000, NIC: 7000000, NER: 26200000, NGA: 223000000, NOR: 5500000,
  OMN: 4600000, PAK: 235000000, PAN: 4400000, PNG: 10300000, PRY: 6800000,
  PER: 34000000, PHL: 117000000, POL: 37800000, PRT: 10300000, QAT: 2700000,
  ROU: 19000000, RUS: 144000000, RWA: 14000000, SAU: 36400000, SEN: 17700000,
  SRB: 6700000, SLE: 8600000, SGP: 5500000, SVK: 5400000, SVN: 2100000,
  SOM: 18100000, ZAF: 60000000, SSD: 11400000, ESP: 47400000, LKA: 22000000,
  SDN: 46800000, SUR: 620000, SWE: 10500000, CHE: 8800000, SYR: 22100000,
  TWN: 23500000, TJK: 10100000, TZA: 65500000, THA: 72000000, TLS: 1400000,
  TGO: 8800000, TTO: 1500000, TUN: 12400000, TUR: 85300000, TKM: 6500000,
  UGA: 48600000, UKR: 37000000, ARE: 9400000, GBR: 67500000, USA: 335000000,
  URY: 3400000, UZB: 35300000, VEN: 28400000, VNM: 100000000, YEM: 34000000,
  ZMB: 20600000, ZWE: 16300000,
}

// HDI data (Human Development Index)
const HDI_DATA: Record<string, number> = {
  NOR: 0.961, CHE: 0.962, ISL: 0.959, DNK: 0.952, SWE: 0.947,
  IRL: 0.945, DEU: 0.942, NLD: 0.941, FIN: 0.940, AUS: 0.946,
  BEL: 0.937, NZL: 0.937, CAN: 0.936, USA: 0.921, GBR: 0.929,
  JPN: 0.920, KOR: 0.929, ISR: 0.915, LUX: 0.927, SVN: 0.918,
  AUT: 0.916, FRA: 0.903, ESP: 0.905, CZE: 0.889, ITA: 0.895,
  EST: 0.890, GRC: 0.887, POL: 0.876, LTU: 0.875, CYP: 0.896,
  HUN: 0.846, PRT: 0.866, SVK: 0.848, ARG: 0.842, CHL: 0.860,
  HRV: 0.858, SAU: 0.875, ROU: 0.821, KWT: 0.831, RUS: 0.822,
  TUR: 0.838, MYS: 0.803, BLR: 0.808, MEX: 0.758, BRA: 0.754,
  CHN: 0.768, THA: 0.800, COL: 0.752, ECU: 0.740, PER: 0.762,
  IRN: 0.774, UKR: 0.734, ZAF: 0.713, EGY: 0.728, IDN: 0.713,
  PHL: 0.699, VNM: 0.726, IND: 0.644, BGD: 0.670, PAK: 0.544,
  NGA: 0.548, KEN: 0.575, GHA: 0.632, CMR: 0.576, TZA: 0.549,
  UGA: 0.550, ETH: 0.498, COD: 0.479, AFG: 0.462, MLI: 0.428,
  NER: 0.394, TCD: 0.394, CAF: 0.387, SSD: 0.385,
}

// Gender Inequality Index (lower is better)
const GII_DATA: Record<string, number> = {
  CHE: 0.019, DNK: 0.021, NOR: 0.016, SWE: 0.023, NLD: 0.025,
  BEL: 0.026, FIN: 0.039, FRA: 0.053, ISL: 0.019, DEU: 0.073,
  AUS: 0.073, CAN: 0.074, GBR: 0.098, JPN: 0.083, KOR: 0.067,
  USA: 0.179, ESP: 0.044, ITA: 0.056, PRT: 0.081, GRC: 0.116,
  POL: 0.115, HUN: 0.233, CZE: 0.136, SVK: 0.191, RUS: 0.203,
  CHN: 0.192, BRA: 0.390, MEX: 0.309, ARG: 0.287, CHL: 0.187,
  TUR: 0.272, IRN: 0.459, SAU: 0.252, EGY: 0.438, IND: 0.490,
  IDN: 0.444, PAK: 0.534, BGD: 0.503, NGA: 0.680, KEN: 0.518,
  ZAF: 0.405, ETH: 0.517, AFG: 0.655, YEM: 0.820,
}

main().catch(console.error)
